<script>
  import {actionsFor,runsFor} from '../lib/fixtures.js';
  import {translate,formatCount,formatWhen} from '../lib/i18n.js';
  import StatusChip from '../lib/StatusChip.svelte';
  export let locale, scenario, navigate;
  $: t=(key,values={})=>translate(locale,key,values);
  $: actions=actionsFor(scenario);
  $: recent=runsFor(scenario).slice(0,4);
  $: attention=scenario==='recovery'||scenario==='blocker'||scenario==='failed';
  function openAction(row){navigate(row.id==='recovery'?'system':'packages',row.id==='recovery'?'':row.id);}
</script>
{#if attention}<div class="attention-notice" role="status"><span class="notice-mark" aria-hidden="true">!</span><div><strong>{t(scenario==='recovery'?'status.recoveryBlocked':scenario==='failed'?'runs.failedTitle':'scenario.blocker')}</strong><p>{t(scenario==='recovery'?'overview.reasonRecovery':scenario==='failed'?'runs.failedHelp':'overview.reasonBuild')}</p></div><button class="button secondary" on:click={() => navigate(scenario==='recovery'?'system':'runs')}>{t('overview.actionReview')}</button></div>{/if}
<div class="overview-headline"><StatusChip label={t(attention?'common.needsReview':'status.systemHealthy')} tone={attention?'warning':'success'} icon={attention?'!':'✓'} /><div class="compact-stats"><span>{t('overview.managed')} <strong>{formatCount(locale,scenario==='empty'?0:scenario==='manyPackages'?28:6)}</strong></span><span>{t('overview.active')} <strong>{formatCount(locale,scenario==='running'?1:0)}</strong></span><span>{t('overview.readyPublish')} <strong>{formatCount(locale,scenario==='empty'?0:2)}</strong></span></div></div>
<div class="overview-grid"><div class="overview-main"><section class="panel"><div class="section-head"><h2>{t('overview.needsAttention')}</h2>{#if actions.length>5}<button class="text-button" on:click={() => navigate('packages')}>{t('common.viewAll',{count:formatCount(locale,actions.length)})}</button>{/if}</div>{#if actions.length===0}<div class="empty-state"><strong>{t('overview.noActions')}</strong><p>{t('overview.noActionsHelp')}</p></div>{:else}<div class="click-list">{#each actions.slice(0,5) as row}<button class="click-row" on:click={() => openAction(row)}><span class="row-status {row.tone}" aria-hidden="true">{row.tone==='danger'?'!':row.tone==='warning'?'●':'✓'}</span><span class="click-main"><strong>{row.id}</strong><small>{t('overview.'+row.reason,{version:row.version||''})}</small></span><span class="row-action">{t('overview.'+row.action)}</span></button>{/each}</div>{/if}</section>
<section class="panel"><div class="section-head"><h2>{t('overview.recent')}</h2><button class="text-button" on:click={() => navigate('runs')}>{t('common.viewAllRuns')}</button></div>{#if recent.length===0}<div class="empty-state"><strong>{t('overview.noRuns')}</strong><p>{t('overview.noRunsHelp')}</p></div>{:else}<div class="click-list">{#each recent as run}<button class="click-row" on:click={() => navigate('runs',run.id)}><span class="row-status {run.status==='failed'?'danger':run.status==='running'?'info':'success'}" aria-hidden="true">{run.status==='failed'?'!':run.status==='running'?'◌':'✓'}</span><span class="click-main"><strong>{run.pkg} · {t('runs.'+run.type)}</strong><small>{formatWhen(locale,run.at)} · {run.version}</small></span><span class="row-action">{t('common.'+(run.status==='recovery'?'blocked':run.status))}</span></button>{/each}</div>{/if}</section></div><aside class="overview-side"><section class="panel compact-panel"><div class="section-head"><h2>{t('overview.activeWork')}</h2>{#if scenario==='running'}<StatusChip label={t('common.running')} tone="info" icon="◌" />{/if}</div>{#if scenario==='running'}<button class="plain-link" on:click={() => navigate('runs','ui-24-running')}><strong>{t('overview.activeBuild',{name:'pocket-id'})}</strong><span>{t('overview.buildActiveHelp')}</span><b>{t('overview.actionOpen')}</b></button>{:else}<p class="muted compact-copy">{t('overview.noActiveHelp')}</p>{/if}</section><section class="panel compact-panel"><div class="section-head"><h2>{t('overview.repository')}</h2><StatusChip label={t('common.online')} tone="success" icon="●" /></div><p class="repo-line">Luminous · main · amd64</p><p class="muted compact-copy">{t('overview.lastPublication')}: {formatWhen(locale,'2026-09-25T09:42:00Z')}</p><button class="text-button" on:click={() => navigate('packages','repository')}>{t('overview.viewRepository')}</button></section></aside></div>
