<script>
  import {tick} from 'svelte';
  import {recipeProfiles,recipeInitialEvidence,newRecipe,toV5Fixture,fromV5Fixture} from '../lib/recipeFixtures.js';
  import {translate,countMessage} from '../lib/i18n.js';
  import Provenance from '../lib/Provenance.svelte';
  import RecipeRows from '../lib/RecipeRows.svelte';
  export let locale,scenario,focusRecipe='',openModal;
  $: t=(key,values={})=>translate(locale,key,values);
  const ids=Object.keys(recipeProfiles);
  let search='',selected='zoraxy',mobileEditor=false,level='plan',confirmed=false,creating=false,createStage='source';
  let stored=structuredClone(recipeProfiles),draft=structuredClone(recipeProfiles.zoraxy),revisions={},evidence=structuredClone(recipeInitialEvidence);
  let jsonDraft='',jsonError='',returnFocus,advancedFocus='',advancedTrigger;
  $: filtered=ids.filter(id=>id.includes(search.toLowerCase())||stored[id].source.repository.toLowerCase().includes(search.toLowerCase()));
  $: saved=selected==='new'?null:stored[selected];
  $: changed=selected==='new'||!!saved&&JSON.stringify(draft)!==JSON.stringify(saved);
  $: stale=!!evidence[selected]&&(changed||(revisions[selected]||0)!==evidence[selected].revision);
  $: proof=stale?null:evidence[selected];
  $: sourceBuild=draft.artifact.mode==='source_build';
  $: upstreamDeb=draft.artifact.mode==='upstream_deb';
  $: prebuilt=draft.artifact.mode==='upstream_archive';
  $: configuredService=draft.service.configured&&!!draft.service.name&&!!draft.service.command;
  $: elfEligible=prebuilt&&draft.artifact.archiveSource==='release_asset'&&draft.pkg.architecture==='amd64'&&draft.install.contentSource==='build_output'&&!!evidence[selected]&&!!saved&&draft.source.repository===saved.source.repository&&draft.artifact.assetName===saved.artifact.assetName&&draft.artifact.archiveSource===saved.artifact.archiveSource&&draft.install.contentSource===saved.install.contentSource&&draft.pkg.architecture===saved.pkg.architecture;
  $: blocker=scenario==='blocker'&&selected==='zoraxy'&&!confirmed;
  $: hooks=Object.entries(draft.install.hooks).filter(([,value])=>value.trim()).map(([key])=>key);
  $: if(focusRecipe&&stored[focusRecipe]&&focusRecipe!==selected)choose(focusRecipe);
  const mappingFields=[{key:'source',label:'recipeUx.sourcePath'},{key:'destination',label:'recipeUx.destinationPath'},{key:'policy',label:'recipeUx.policy',options:[{value:'dpkg_conffile',label:'recipeUx.conffile'},{value:'replace',label:'recipeUx.replace'},{value:'create_if_missing',label:'recipeUx.createMissing'}]},{key:'owner',label:'recipeUx.ownerUser'},{key:'group',label:'recipeUx.ownerGroup'},{key:'mode',label:'recipeUx.mode'}];
  const directoryFields=[{key:'path',label:'recipeUx.path'},{key:'owner',label:'recipeUx.ownerUser'},{key:'group',label:'recipeUx.ownerGroup'},{key:'mode',label:'recipeUx.mode',options:['0755','0750','0700'].map(value=>({value,label:value}))}];
  const envFields=[{key:'key',label:'recipeUx.variable'},{key:'value',label:'recipeUx.value'}];
  const changeFields=[{key:'operation',label:'recipeUx.operation',options:['replace','insert_before','insert_after','remove','create_file','remove_file'].map(value=>({value,label:'recipeUx.op.'+value}))},{key:'path',label:'recipeUx.path'},{key:'search',label:'recipeUx.searchText',showWhen:row=>!['create_file','remove_file'].includes(row.operation)},{key:'content',label:'recipeUx.content',multiline:true,showWhen:row=>row.operation!=='remove_file'&&row.operation!=='remove'}];
  const overrideFields=[{key:'soname',label:'recipeUx.soname'},{key:'action',label:'recipeUx.action',options:[{value:'ignore',label:'recipeUx.ignore'},{value:'manual',label:'recipeUx.manualRelation'}]},{key:'reason',label:'recipeUx.reason'},{key:'relation',label:'recipeUx.relation'}];
  const repositoryFields=[{key:'id',label:'recipeUx.id'},{key:'uri',label:'recipeUx.uri'},{key:'suite',label:'recipeUx.suite'},{key:'components',label:'recipeUx.components'},{key:'armored',label:'recipeUx.publicKey',multiline:true}];
  async function choose(id){advancedFocus='';creating=false;selected=id;draft=structuredClone(stored[id]);level='plan';mobileEditor=true;confirmed=false;jsonDraft='';await tick();}
  function startCreate(){advancedFocus='';creating=true;createStage='source';selected='new';draft=newRecipe();level='customize';mobileEditor=true;confirmed=false;}
  function cancel(){draft=selected==='new'?newRecipe():structuredClone(stored[selected]);jsonError='';}
  function save(){if(!draft.source.repository.match(/^[^/\s]+\/[^/\s]+$/)){jsonError=t('recipeUx.invalidRepository');return;}if(draft.install.directories.some(row=>!['/etc/','/var/lib/','/var/log/'].some(root=>row.path===root+draft.id||row.path.startsWith(root+draft.id+'/')))){jsonError=t('recipeUx.invalidDirectory');return;}if(draft.install.contentSource==='configured_files'&&draft.install.mappings.some(row=>!row.source||!row.destination.startsWith('/'))){jsonError=t('recipeUx.invalidMapping');return;}if(selected==='new'){const id=draft.id.trim().toLowerCase();if(!/^[a-z0-9_.+-]+$/.test(id)||stored[id]){jsonError=t('recipeUx.invalidId');return;}stored={...stored,[id]:structuredClone({...draft,id})};selected=id;revisions={...revisions,[id]:1};draft=structuredClone(stored[id]);if(creating){createStage='test';level='plan';}}else{stored={...stored,[selected]:structuredClone(draft)};revisions={...revisions,[selected]:(revisions[selected]||0)+1};}jsonError='';}
  function fixtureTest(){if(changed||selected==='new')return; if(creating&&createStage==='test')createStage='plan';evidence={...evidence,[selected]:{kind:'test',source:draft.source.ref||draft.artifact.assetName||'fixture source identity',project:sourceBuild?'Source build detected':'Prebuilt asset',revision:revisions[selected]||0}};openModal('test');}
  function setLevel(next){advancedFocus='';if(next==='expert'&&!jsonDraft)jsonDraft=JSON.stringify(toV5Fixture(draft),null,2);level=next;window.scrollTo({top:0,behavior:'instant'});}
  async function openAdvanced(name){advancedTrigger=document.activeElement;advancedFocus=name;await tick();document.querySelector('.recipe-advanced-group.active h3')?.focus();}
  async function backAdvanced(){advancedFocus='';await tick();advancedTrigger?.focus();}
  function configureService(){draft.service={...draft.service,configured:true,name:draft.id+'.service',command:'/usr/bin/'+draft.id};}
  function setMode(mode){draft.artifact.mode=mode;if(mode==='upstream_deb')draft.artifact.archiveSource='auto';}
  function applyJson(){try{const parsed=JSON.parse(jsonDraft);if(parsed.name!==draft.id)throw Error(t('recipeUx.idImmutable'));draft=fromV5Fixture(parsed);jsonError='';}catch(error){jsonError=error.message;}}
  function exportJson(){const blob=new Blob([JSON.stringify(toV5Fixture(draft),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${draft.id}.fixture.json`;link.click();URL.revokeObjectURL(url);}
  async function importJson(event){const file=event.currentTarget.files?.[0];if(!file)return;if(file.size>1024*1024){jsonError=t('recipeUx.fileTooLarge');return;}jsonDraft=await file.text();jsonError='';}
  async function openJson(){returnFocus=document.activeElement;jsonDraft=JSON.stringify(toV5Fixture(draft),null,2);level='expert';await tick();document.querySelector('#recipe-json')?.focus();}
  function keydown(event){if(event.key==='Escape'&&level==='expert'&&document.activeElement?.closest('.recipe-json-box')){event.preventDefault();setLevel('plan');tick().then(()=>returnFocus?.focus());}}
</script>
<svelte:window on:keydown={keydown} />
<div class="recipe-layout" class:mobile-editor={mobileEditor}>
  <aside class="panel recipe-picker"><div class="section-head"><h2>{t('nav.recipes')}</h2><span class="count-label">{countMessage(locale,'recipes.recipeCount.one','recipes.recipeCount.other',filtered.length)}</span></div><label class="search-label"><span>{t('recipes.search')}</span><input type="search" bind:value={search} placeholder={t('common.search')} /></label><div class="selection-list">{#each filtered as id}<button class:selected={selected===id} aria-current={selected===id?'true':undefined} on:click={() => choose(id)}><strong>{id}</strong><small>{stored[id].source.repository}</small></button>{/each}</div><button class="button secondary recipe-create" on:click={startCreate}>+ {t('recipeUx.create')}</button></aside>
  <div class="recipe-editor"><button class="back-button mobile-only" on:click={() => mobileEditor=false}>← {t('recipes.back')}</button>
    <div class="editor-head"><div><p class="detail-breadcrumb">{t('nav.recipes')} / <strong>{selected==='new'?t('recipeUx.create'):draft.id}</strong></p><h2>{selected==='new'?t('recipeUx.create'):draft.id}</h2><p>{draft.source.repository||t('recipeUx.sourcePending')} · {t(draft.active?'recipeUx.active':'recipeUx.inactive')}</p></div><div class="editor-actions"><button class="button secondary" on:click={openJson}>{t('recipes.json')}</button><button class="button secondary" on:click={exportJson}>{t('recipes.export')}</button></div></div>
    <nav class="recipe-levels" aria-label={t('recipeUx.sections')}>{#each ['plan','customize','advanced','expert'] as section}<button class:active={level===section} aria-current={level===section?'page':undefined} on:click={() => setLevel(section)}>{t('recipeUx.'+section)}</button>{/each}</nav>
    {#if creating}<div class="recipe-flow"><span class:current={createStage==='source'}>{t('recipeUx.flowSource')}</span><span class:current={createStage==='test'}>{t('recipeUx.flowTest')}</span><span class:current={createStage==='plan'}>{t('recipeUx.flowPlan')}</span><span class:current={createStage==='customize'}>{t('recipeUx.flowCustomize')}</span><span>{t('recipeUx.flowBuild')}</span></div>{/if}
    {#if changed}<div class="recipe-savebar" role="status"><strong>{t('editor.unsaved')}</strong><div><button class="button secondary" on:click={cancel}>{t('editor.cancel')}</button><button class="button primary" on:click={save}>{t('editor.save')}</button></div></div>{/if}
    {#if jsonError}<p class="field-error" role="alert">{jsonError}</p>{/if}
    {#if level==='plan'}
      <section class="panel recipe-plan"><div class="section-head"><div><h3>{t('recipes.planSummary')}</h3><p class="muted">{t('recipeUx.planHelp')}</p></div><Provenance {locale} kind={proof?'Resolved':'Unknown'} /></div>
        {#if stale}<div class="inline-alert" role="status"><strong>{t('recipeUx.stale')}</strong><p>{t('recipeUx.staleHelp')}</p></div>{:else if proof}<div class="inline-note">{t('recipeUx.matchingEvidence')} · {proof.kind==='build'?'Build':'Test'} · {proof.source}</div>{:else}<div class="recipe-pending">{t('recipeUx.noEvidence')}</div>{/if}
        <div class="plan-rows">
          <div><span>{t('recipes.planSource')}</span><strong>{draft.source.repository||t('recipeUx.sourcePending')} · {draft.source.tracking}</strong><Provenance {locale} kind="Configured" /></div>
          <div><span>{t('recipes.exact')}</span><strong>{proof?proof.source:t('recipes.notResolved')}</strong><Provenance {locale} kind={proof?'Resolved':'Unknown'} /></div>
          <div><span>{t('recipes.detected')}</span><strong>{proof?proof.project:t('recipeUx.pendingTest')}</strong><Provenance {locale} kind={proof?'Detected':'Unknown'} /></div>
          <div><span>{t('recipes.planBuild')}</span><strong>{sourceBuild?draft.build.commands.length?draft.build.commands.join(' → '):t('recipeUx.noCommands'):upstreamDeb?t('recipeUx.registerDeb'):t('recipes.noCompile')}</strong><Provenance {locale} kind={sourceBuild?'Configured':'Default'} /></div>
          <div><span>{t('recipes.planOutput')}</span><strong>{sourceBuild?(draft.build.outputs.join(', ')||t('recipeUx.wholeSource')):upstreamDeb?t('recipeUx.upstreamArtifact'):(draft.artifact.include.join(', ')||draft.artifact.assetName||t('recipeUx.pendingTest'))}</strong><Provenance {locale} kind={proof?.kind==='build'?'Effective':'Configured'} /></div>
          {#if !upstreamDeb}<div><span>{t('recipes.planInstall')}</span><strong>{draft.install.contentSource==='configured_files'?draft.install.mappings.map(row=>row.destination).join(', ')||t('recipeUx.noMappings'):draft.install.destination||t('recipeUx.destinationPending')}</strong><Provenance {locale} kind="Configured" /></div><div><span>{t('recipes.planService')}</span><strong>{configuredService?`${draft.service.name} · ${draft.service.command} · ${t(draft.service.enabled?'recipeUx.enabledAtInstall':'recipeUx.disabledAtInstall')}`:t('recipes.noService')}</strong><Provenance {locale} kind="Configured" /></div>
          <div><span>{t('recipeUx.identityEffects')}</span><strong>{draft.install.owner.user}:{draft.install.owner.group} · {draft.install.account.createUser?t('recipeUx.accountCreated'):t('recipeUx.accountExisting')}{configuredService?` · systemd ${draft.service.user||'root'}:${draft.service.group||'root'}`:''}</strong><Provenance {locale} kind="Configured" /></div>{/if}
          <div><span>{t('recipes.planDependencies')}</span><strong>{proof?.kind==='build'&&proof.depends?proof.depends.join(', '):draft.pkg.runtimeDependencies.length?draft.pkg.runtimeDependencies.join(', '):t('recipes.runtimeAfter')}{draft.pkg.elfEnabled?' · '+t('recipeUx.elfAtBuild'):''}</strong><Provenance {locale} kind={proof?.kind==='build'?'Effective':'Unknown'} /></div>
          {#if draft.automation.enabled||Object.values(draft.resourceLimits).some(Boolean)}<div><span>{t('recipeUx.operationalPolicy')}</span><strong>{draft.automation.enabled?draft.automation.policy:t('recipeUx.manual')} · {Object.values(draft.resourceLimits).filter(Boolean).length} {t('recipeUx.limitsSet')}</strong><Provenance {locale} kind="Configured" /></div>{/if}
          {#if hooks.length}<div><span>{t('recipeUx.lifecycle')}</span><strong>{hooks.join(', ')}</strong><Provenance {locale} kind="Configured" /></div>{/if}
        </div>
        {#if selected==='pocket-id'}<div class="inline-alert"><strong>{t('recipeUx.envWarning')}</strong><p>{t('recipeUx.secretGap')}</p></div>{/if}
        {#if selected==='zoraxy'}<div class="inline-alert"><strong>{t('recipeUx.optWarning')}</strong><p>{t('recipes.dirReason')}</p></div>{/if}
        {#if blocker}<div class="inline-alert" role="alert"><strong>{t('recipes.dirBlocker')}</strong><p>{t('recipes.dirReason')}</p><button class="button secondary" on:click={() => confirmed=true}>{t('recipes.confirmDir')}</button></div>{/if}
      </section>
      {#if creating&&createStage==='plan'}<button class="button primary recipe-continue" on:click={() => {createStage='customize';setLevel('customize');}}>{t('recipeUx.continueCustomize')} →</button>{/if}
      <section class="panel recipe-next"><h3>{t('recipes.next')}</h3><p>{t('recipes.testBoundary')}</p><div><button class="button primary" disabled={changed||selected==='new'||blocker||!draft.active||scenario==='recovery'} on:click={fixtureTest}>{t('recipes.testPlan')} →</button><button class="button secondary" disabled={changed||selected==='new'||blocker||!draft.active||scenario==='recovery'||creating&&createStage!=='customize'} on:click={() => openModal('build')}>{t('recipes.buildPackage')}</button></div></section>
    {:else if level==='customize'}
      <section class="panel recipe-section"><h3>{t('recipeUx.sourceAndArtifact')}</h3><div class="recipe-form-grid">{#if selected==='new'}<label>{t('recipeUx.recipeId')}<input bind:value={draft.id} /></label>{/if}<label>{t('recipes.repo')}<input bind:value={draft.source.repository} placeholder="owner/repository" /></label><label>{t('recipes.tracking')}<select bind:value={draft.source.tracking}><option value="latest_release">{t('recipeUx.latestRelease')}</option><option value="tag">{t('recipeUx.tag')}</option><option value="manual">{t('recipeUx.manual')}</option></select></label>{#if draft.source.tracking!=='latest_release'}<label>{t('recipeUx.ref')}<input bind:value={draft.source.ref} /></label>{/if}<label>{t('recipes.sourceType')}<select value={draft.artifact.mode} on:change={(event)=>setMode(event.currentTarget.value)}><option value="source_build">{t('recipeUx.sourceBuild')}</option><option value="upstream_archive">{t('recipeUx.archiveOrAsset')}</option><option value="upstream_deb">{t('recipes.upstreamDeb')}</option></select></label>{#if prebuilt}<label>{t('recipeUx.archiveSource')}<select bind:value={draft.artifact.archiveSource}><option value="release_asset">{t('recipes.releaseAsset')}</option><option value="github_source">{t('recipes.sourceArchive')}</option><option value="auto">{t('recipeUx.automatic')}</option></select></label>{#if draft.artifact.archiveSource==='release_asset'}<label>{t('recipeUx.assetName')}<input bind:value={draft.artifact.assetName} /></label>{/if}{/if}{#if upstreamDeb}<label>{t('recipeUx.assetPattern')}<input bind:value={draft.artifact.namePattern} /></label>{/if}</div></section>
      {#if !creating||createStage==='customize'}
      {#if sourceBuild}<section class="panel recipe-section"><h3>{t('recipeUx.buildAndOutput')}</h3><RecipeRows {locale} title={t('recipes.commands')} bind:rows={draft.build.commands} ordered empty={t('recipeUx.noCommands')} /><label class="recipe-label">{t('recipeUx.outputMode')}<select bind:value={draft.build.outputMode}><option value="source">{t('recipeUx.wholeSource')}</option><option value="path">{t('recipeUx.onePath')}</option><option value="paths">{t('recipeUx.paths')}</option></select></label>{#if draft.build.outputMode!=='source'}<RecipeRows {locale} title={t('recipes.outputPaths')} bind:rows={draft.build.outputs} ordered empty={t('recipeUx.noOutputs')} />{/if}</section>{/if}
      <section class="panel recipe-section"><h3>{t('recipes.packageMeta')}</h3><label class="recipe-check"><input type="checkbox" bind:checked={draft.active} />{t('recipeUx.active')}</label><div class="recipe-form-grid"><label>{t('recipeUx.description')}<input bind:value={draft.pkg.description} /></label><label>{t('recipeUx.architecture')}<select bind:value={draft.pkg.architecture}><option value="all">all</option><option value="amd64">amd64</option><option value="arm64">arm64</option><option value="armhf">armhf</option></select></label></div></section>
      {#if !upstreamDeb}<section class="panel recipe-section"><h3>{t('recipes.install')}</h3><div class="recipe-form-grid"><label>{t('recipeUx.contentSource')}<select bind:value={draft.install.contentSource}><option value="build_output">{t('recipeUx.buildOutput')}</option><option value="configured_files">{t('recipeUx.configuredFiles')}</option></select></label>{#if draft.install.contentSource==='build_output'}<label>{t('recipes.destination')}<input bind:value={draft.install.destination} placeholder="/opt/package" /></label>{:else}<p class="recipe-context">{t('recipeUx.mappingsOnly')}</p>{/if}</div>{#if draft.install.contentSource==='configured_files'}<RecipeRows {locale} title={t('recipes.mappings')} bind:rows={draft.install.mappings} fields={mappingFields} empty={t('recipeUx.noMappings')} />{/if}</section>
      <section class="panel recipe-section"><h3>{t('recipes.service')}</h3>{#if !configuredService}<p class="recipe-empty">{t('recipes.noService')}</p><button class="button secondary" on:click={configureService}>{t('recipeUx.configureService')}</button>{:else}<div class="recipe-form-grid"><label>{t('recipeUx.serviceName')}<input bind:value={draft.service.name} /></label><label>{t('recipeUx.serviceCommand')}<input bind:value={draft.service.command} /></label><label>{t('recipeUx.systemdUser')}<input bind:value={draft.service.user} /></label><label>{t('recipeUx.systemdGroup')}<input bind:value={draft.service.group} /></label><label>{t('recipeUx.restart')}<select bind:value={draft.service.restart}><option value="on-failure">on-failure</option><option value="always">always</option><option value="no">no</option></select></label><label class="recipe-check"><input type="checkbox" bind:checked={draft.service.enabled} />{t('recipeUx.enableAtInstall')}</label></div>{/if}</section>
      <section class="panel recipe-section"><RecipeRows {locale} title={t('recipes.depends')} bind:rows={draft.pkg.runtimeDependencies} empty={t('recipeUx.noManualDepends')} /></section>{/if}
      {/if}
    {:else if level==='advanced'}
      <div class="recipe-advanced-navigation mobile-only">{#if advancedFocus}<button class="back-button" on:click={backAdvanced}>← {t('recipeUx.backAdvanced')}</button>{:else}<h3>{t('recipeUx.advancedSections')}</h3><div class="recipe-advanced-menu"><button on:click={() => openAdvanced('source')}>{t('recipeUx.sourceDetails')} →</button>{#if sourceBuild}<button on:click={() => openAdvanced('build')}>{t('recipeUx.buildOperations')} →</button>{/if}<button on:click={() => openAdvanced('package')}>{t('recipeUx.packageDetails')} →</button>{#if !upstreamDeb}<button on:click={() => openAdvanced('files')}>{t('recipeUx.filesAndIdentity')} →</button>{#if configuredService}<button on:click={() => openAdvanced('service')}>{t('recipeUx.serviceOperations')} →</button>{/if}{/if}<button on:click={() => openAdvanced('resources')}>{t('recipes.limits')} →</button><button on:click={() => openAdvanced('automation')}>{t('recipes.automation')} →</button>{#if elfEligible||draft.pkg.elfEnabled}<button on:click={() => openAdvanced('dependencies')}>{t('recipeUx.dependencies')} →</button>{/if}</div>{/if}</div>
      <section class="panel recipe-section recipe-advanced-group" class:active={advancedFocus==='source'}><h3 tabindex="-1">{t('recipeUx.sourceDetails')}</h3><div class="recipe-form-grid"><label>{t('recipeUx.versionSource')}<select bind:value={draft.source.versionSource}><option value="tag">tag</option><option value="release_name">release name</option><option value="regex">regex</option></select></label>{#if draft.source.versionSource==='regex'}<label>{t('recipeUx.expression')}<input bind:value={draft.source.expression} /></label>{/if}{#if prebuilt&&draft.artifact.archiveSource==='github_source'}<label>{t('recipeUx.archiveFormat')}<select bind:value={draft.artifact.format}><option>tar.gz</option><option>zip</option></select></label>{/if}{#if prebuilt&&draft.artifact.archiveSource==='release_asset'}<label>{t('recipeUx.assetSelection')}<select bind:value={draft.artifact.assetSelection}><option value="exact">{t('recipeUx.exact')}</option><option value="pattern">{t('recipeUx.pattern')}</option></select></label>{#if draft.artifact.assetSelection==='pattern'}<label>{t('recipeUx.assetPattern')}<input bind:value={draft.artifact.namePattern} /></label>{/if}{/if}{#if upstreamDeb}<label class="recipe-check"><input type="checkbox" bind:checked={draft.artifact.matchPackage} />{t('recipeUx.matchPackage')}</label><label class="recipe-check"><input type="checkbox" bind:checked={draft.artifact.matchVersion} />{t('recipeUx.matchVersion')}</label>{/if}</div>{#if prebuilt}<label class="recipe-label">{t('recipeUx.payloadMode')}<select bind:value={draft.artifact.payloadMode}><option value="paths">{t('recipeUx.paths')}</option><option value="entire_archive">{t('recipeUx.wholeArchive')}</option></select></label>{#if draft.artifact.payloadMode==='paths'}<RecipeRows {locale} title={t('recipeUx.includePaths')} bind:rows={draft.artifact.include} empty={t('recipeUx.pendingTest')} />{/if}<RecipeRows {locale} title={t('recipeUx.excludePaths')} bind:rows={draft.artifact.exclude} />{/if}</section>
      {#if sourceBuild}<section class="panel recipe-section recipe-advanced-group" class:active={advancedFocus==='build'}><h3 tabindex="-1">{t('recipeUx.buildOperations')}</h3><div class="recipe-form-grid"><label>{t('recipes.workingDir')}<input bind:value={draft.build.workingDirectory} /></label><label>{t('recipeUx.inactivitySeconds')}<input type="number" min="1" max="86400" bind:value={draft.build.inactivityTimeout} /></label><label>{t('recipeUx.maximumSeconds')}<input type="number" min="1" max="604800" bind:value={draft.build.maximumRuntime} /></label></div><RecipeRows {locale} title={t('recipes.environment')} bind:rows={draft.build.environment} fields={envFields} empty={t('recipeUx.inheritedEnvironment')} /><RecipeRows {locale} title={t('recipeUx.buildDependencies')} bind:rows={draft.build.extraDependencies} /><RecipeRows {locale} title={t('recipes.sourceChanges')} bind:rows={draft.build.sourceChanges} fields={changeFields} ordered /><RecipeRows {locale} title={t('recipes.ensureDirs')} bind:rows={draft.build.ensureDirectories} guidance={t('recipeUx.outputCoverage')} /></section>{/if}
      <section class="panel recipe-section recipe-advanced-group" class:active={advancedFocus==='package'}><h3 tabindex="-1">{t('recipeUx.packageDetails')}</h3><div class="recipe-form-grid"><label>{t('recipeUx.revision')}<input bind:value={draft.pkg.revision} /></label><label>{t('recipeUx.section')}<input bind:value={draft.pkg.section} /></label><label>{t('recipeUx.priority')}<select bind:value={draft.pkg.priority}><option>required</option><option>important</option><option>standard</option><option>optional</option><option>extra</option></select></label><label>{t('recipeUx.maintainer')}<input bind:value={draft.pkg.maintainer} /></label><label>{t('recipeUx.artifactArchitecture')}<select bind:value={draft.artifact.architecture}><option>amd64</option><option>arm64</option><option>armhf</option><option>all</option></select></label></div></section>
      {#if !upstreamDeb}<section class="panel recipe-section recipe-advanced-group" class:active={advancedFocus==='files'}><h3 tabindex="-1">{t('recipeUx.filesAndIdentity')}</h3>{#if draft.install.contentSource!=='configured_files'}<RecipeRows {locale} title={t('recipes.mappings')} bind:rows={draft.install.mappings} fields={mappingFields} />{/if}<div class="recipe-form-grid"><fieldset><legend>{t('recipeUx.filesOwnedBy')}</legend><label>{t('recipeUx.ownerUser')}<input bind:value={draft.install.owner.user} /></label><label>{t('recipeUx.ownerGroup')}<input bind:value={draft.install.owner.group} /></label></fieldset><fieldset><legend>{t('recipeUx.accountProvision')}</legend><label>{t('recipeUx.accountUser')}<input bind:value={draft.install.account.user} /></label><label>{t('recipeUx.accountGroup')}<input bind:value={draft.install.account.group} /></label><label class="recipe-check"><input type="checkbox" bind:checked={draft.install.account.createUser} />{t('recipeUx.createUser')}</label><label class="recipe-check"><input type="checkbox" bind:checked={draft.install.account.createGroup} />{t('recipeUx.createGroup')}</label></fieldset></div><div class="recipe-form-grid"><label>{t('recipeUx.directoryMode')}<select bind:value={draft.install.directoryMode}><option>0755</option><option>0750</option><option>0700</option></select></label><label>{t('recipeUx.fileMode')}<select bind:value={draft.install.fileMode}><option>0644</option><option>0640</option><option>0600</option></select></label></div><RecipeRows {locale} title={t('recipes.directories')} bind:rows={draft.install.directories} fields={directoryFields} guidance={t('recipeUx.acceptedRoots')} /></section>
      {#if configuredService}<section class="panel recipe-section recipe-advanced-group" class:active={advancedFocus==='service'}><h3 tabindex="-1">{t('recipeUx.serviceOperations')}</h3><div class="recipe-form-grid"><label>{t('recipes.workingDir')}<input bind:value={draft.service.workingDirectory} /></label><label>{t('recipeUx.serviceType')}<select bind:value={draft.service.type}><option>simple</option><option>exec</option><option>forking</option><option>oneshot</option><option>notify</option><option>dbus</option></select></label></div><p class="recipe-context">{t('recipeUx.envFileReference')}</p><RecipeRows {locale} title={t('recipes.envFiles')} bind:rows={draft.service.environmentFiles} /><RecipeRows {locale} title={t('recipes.environment')} bind:rows={draft.service.environment} fields={envFields} /><div class="recipe-relation-grid"><RecipeRows {locale} title="After" bind:rows={draft.service.after} /><RecipeRows {locale} title="Wants" bind:rows={draft.service.wants} /><RecipeRows {locale} title="Requires" bind:rows={draft.service.requires} /><RecipeRows {locale} title="Conflicts" bind:rows={draft.service.conflicts} /></div></section>{/if}
      <section class="panel recipe-section recipe-advanced-group" class:active={advancedFocus==='resources'}><h3 tabindex="-1">{t('recipes.limits')}</h3><p class="recipe-context">{t('recipeUx.inheritedLimits')}</p><div class="recipe-form-grid"><label>{t('recipeUx.memoryBytes')}<input type="number" min="1" placeholder={t('recipeUx.inherited')} bind:value={draft.resourceLimits.memory} /></label><label>{t('recipeUx.tasks')}<input type="number" min="1" placeholder={t('recipeUx.inherited')} bind:value={draft.resourceLimits.tasks} /></label><label>{t('recipeUx.cpuPercent')}<input type="number" min="1" placeholder={t('recipeUx.inherited')} bind:value={draft.resourceLimits.cpu} /></label><label>{t('recipeUx.ioRead')}<input type="number" min="1" placeholder={t('recipeUx.inherited')} bind:value={draft.resourceLimits.ioRead} /></label><label>{t('recipeUx.ioWrite')}<input type="number" min="1" placeholder={t('recipeUx.inherited')} bind:value={draft.resourceLimits.ioWrite} /></label></div></section>
      <section class="panel recipe-section recipe-advanced-group" class:active={advancedFocus==='automation'}><h3 tabindex="-1">{t('recipes.automation')}</h3><label class="recipe-check"><input type="checkbox" bind:checked={draft.automation.enabled} />{t('recipeUx.enableAutomation')}</label>{#if draft.automation.enabled}<label class="recipe-label">{t('recipeUx.automationPolicy')}<select bind:value={draft.automation.policy}>{#each ['manual','detect','test','build','build_validate','full'] as policy}<option value={policy}>{policy}</option>{/each}</select></label>{/if}</section>{/if}
      {#if elfEligible||draft.pkg.elfEnabled}<section class="panel recipe-section recipe-elf recipe-advanced-group" class:active={advancedFocus==='dependencies'}><h3 tabindex="-1">{t('recipeUx.dependencies')}</h3><h4>{t('recipeUx.elfTitle')}</h4>{#if elfEligible}<p>{t('recipeUx.elfAvailable')}</p><label class="recipe-check"><input type="checkbox" bind:checked={draft.pkg.elfEnabled} />{t('recipeUx.enableElf')}</label>{:else}<p class="field-error">{t('recipeUx.elfNoCopiedPayload')}</p>{/if}</section>{/if}
    {:else}
      <section class="panel recipe-section"><h3>{t('recipeUx.lifecycle')} — {hooks.length?hooks.join(', '):t('recipeUx.none')}</h3><p class="recipe-context">{t('recipeUx.hooksHelp')}</p><div class="recipe-hook-grid">{#each [['preinst','recipeUx.preinst'],['postinst','recipeUx.postinst'],['prerm','recipeUx.prerm'],['postrm','recipeUx.postrm']] as [key,label]}<label><span>{t(label)} · <code>{key}</code></span><textarea rows="5" bind:value={draft.install.hooks[key]} placeholder={t('recipeUx.none')}></textarea></label>{/each}</div></section>
      {#if configuredService}<section class="panel recipe-section"><h3>{t('recipeUx.advancedSystemd')}</h3><div class="recipe-form-grid">{#each [['restartSec','RestartSec'],['timeoutStartSec','TimeoutStartSec'],['timeoutStopSec','TimeoutStopSec'],['killSignal','KillSignal'],['standardOutput','StandardOutput'],['standardError','StandardError'],['limitNofile','LimitNOFILE'],['syslogIdentifier','SyslogIdentifier']] as [key,label]}<label>{label}<input bind:value={draft.service[key]} /></label>{/each}<label>KillMode<select bind:value={draft.service.killMode}><option value="">{t('recipeUx.inherited')}</option><option>control-group</option><option>mixed</option><option>process</option><option>none</option></select></label></div><RecipeRows {locale} title="AmbientCapabilities" bind:rows={draft.service.ambientCapabilities} /><RecipeRows {locale} title="ExecStartPre" bind:rows={draft.service.execStartPre} ordered /><RecipeRows {locale} title="ExecStartPost" bind:rows={draft.service.execStartPost} ordered /><RecipeRows {locale} title="ExecStop" bind:rows={draft.service.execStop} ordered /></section>{/if}
      {#if draft.pkg.overrides.length||(draft.pkg.elfEnabled&&elfEligible&&proof?.kind==='build')}<section class="panel recipe-section"><h3>{t('recipeUx.sonameOverrides')}</h3><RecipeRows {locale} title={t('recipeUx.sonameOverrides')} bind:rows={draft.pkg.overrides} fields={overrideFields} /></section>{/if}
      <section class="panel recipe-section"><h3>{t('recipeUx.runtimeApt')}</h3><RecipeRows {locale} title={t('recipeUx.runtimeApt')} bind:rows={draft.runtimeAptRepositories} fields={repositoryFields} empty={t('recipeUx.noExtraApt')} /></section>
      <section class="panel recipe-section recipe-json-box"><h3>{t('recipeUx.rawFixture')}</h3><p class="recipe-context">{t('recipeUx.jsonFixtureHelp')}</p><div class="recipe-json-actions"><label class="button secondary">{t('recipes.import')}<input type="file" accept="application/json,.json" on:change={importJson} /></label><button class="button secondary" on:click={exportJson}>{t('recipes.export')}</button><button class="button secondary" on:click={() => jsonDraft=JSON.stringify(toV5Fixture(draft),null,2)}>{t('recipeUx.loadJson')}</button></div><label class="recipe-label" for="recipe-json">{t('recipes.json')}</label><textarea id="recipe-json" rows="12" bind:value={jsonDraft}></textarea><button class="button primary" disabled={!jsonDraft} on:click={applyJson}>{t('recipeUx.applyFixture')}</button></section>
    {/if}
  </div>
</div>
