<script>
  import {runsFor,stageKeys} from '../lib/fixtures.js';
  import {translate,formatCount,formatWhen,countMessage} from '../lib/i18n.js';
  import StatusChip from '../lib/StatusChip.svelte';
  import RunPoller from '../lib/RunPoller.svelte';
  export let locale,scenario,navigate,focusRun='',openModal;
  $: t=(key,values={})=>translate(locale,key,values);
  let search='';
  let filter='all';
  let selectedId='ui-24-validated';
  let mobileDetail=false;
  let following=true;
  let verbosity='normal';
  let diagnosisOpen=false;
  $: rows=runsFor(scenario);
  $: filtered=rows.filter(row=>(row.pkg.toLowerCase().includes(search.toLowerCase())||row.id.toLowerCase().includes(search.toLowerCase()))&&(filter==='all'||row.status===filter));
  $: selected=rows.find(row=>row.id===selectedId)||rows[0];
  $: if(focusRun && rows.some(row=>row.id===focusRun)){selectedId=focusRun;mobileDetail=true;}
  $: if(scenario==='running')selectedId='ui-24-running';
  $: if(scenario==='failed')selectedId='ui-24-failed';
  $: if(scenario==='recovery')selectedId='ui-24-recovery';
  function select(row){selectedId=row.id;mobileDetail=true;diagnosisOpen=false;}
  function stageState(run,index){if(run.status==='published')return 'completed';if(run.status==='failed')return index<6?'completed':index===6?'failed':'queued';if(run.status==='validated')return index<=6?'completed':'queued';if(run.status==='running')return index<3?'completed':index===3?'running':'queued';return index<3?'completed':'queued';}
  function tone(status){return status==='failed'||status==='recovery'?'danger':status==='running'?'info':status==='queued'||status==='prepared'?'warning':status==='cancelled'?'neutral':'success';}
</script>
<div class="run-layout" class:mobile-detail={mobileDetail}><section class="panel run-list"><div class="section-head"><h2>{t('runs.run')}</h2><span class="count-label">{formatCount(locale,filtered.length)} / {formatCount(locale,rows.length)}</span></div><div class="filters run-filters"><label><span>{t('runs.search')}</span><input type="search" bind:value={search} placeholder={t('common.search')} /></label><label><span>{t('runs.filter')}</span><select bind:value={filter}><option value="all">{t('common.all')}</option>{#each ['running','queued','validated','published','failed','recovery','cancelled','prepared','completed'] as status}<option value={status}>{t('common.'+(status==='recovery'?'blocked':status))}</option>{/each}</select></label></div>
{#if filtered.length===0}<div class="empty-state"><strong>{t('runs.noRuns')}</strong></div>{:else}<div class="selection-list run-selection">{#each filtered as row}<button class:selected={selected?.id===row.id} aria-current={selected?.id===row.id?'true':undefined} on:click={() => select(row)}><span><strong>{row.pkg}</strong><small>{t('runs.'+row.type)} · {formatWhen(locale,row.at)}</small></span><StatusChip label={t('common.'+(row.status==='recovery'?'blocked':row.status))} tone={tone(row.status)} icon={row.status==='failed'?'!':'●'} /></button>{/each}</div>{/if}</section>
{#if selected}<div class="run-detail"><button class="back-button mobile-only" on:click={() => mobileDetail=false}>← {t('runs.back')}</button><section class="panel"><p class="detail-breadcrumb">{t('nav.runs')} / <strong>{selected.id}</strong></p><div class="run-title"><div><h2>{selected.pkg}</h2><p class="muted">{t('runs.'+selected.type)} · {selected.version}</p></div><StatusChip label={t('common.'+(selected.status==='recovery'?'blocked':selected.status))} tone={tone(selected.status)} icon={selected.status==='failed'?'!':'●'} /></div><div class="detail-facts"><div><span>{t('runs.started')}</span><strong>{formatWhen(locale,selected.at)}</strong></div><div><span>{t('runs.snapshot')}</span><strong>{selected.pkg} · {selected.version}</strong></div><div><span>{t('common.type')}</span><strong>{t('runs.'+selected.type)}</strong></div></div>
{#if selected.status==='recovery'}<div class="inline-alert"><strong>{t('runs.recoveryTitle')}</strong><p>{t('runs.recoveryHelp')}</p></div>{:else if selected.status==='failed'}<div class="inline-alert"><strong>{t('runs.failedTitle')}</strong><p>{t('runs.failedHelp')}</p><button class="button secondary" on:click={() => diagnosisOpen=!diagnosisOpen}>{t('runs.diagnose')}</button></div>{#if diagnosisOpen}<div class="diagnosis-panel"><strong>{t('runs.diagnosisTitle')}</strong><dl><div><dt>{t('runs.diagnosisStage')}</dt><dd>{t('runs.stage.validate')}</dd></div><div><dt>{t('runs.diagnosisCode')}</dt><dd><code>DEPENDENCY_UNRESOLVED</code></dd></div><div><dt>{t('runs.diagnosisContext')}</dt><dd><code>libexample.so.1</code> · archive-agent 5.0.0-3</dd></div></dl><p>{t('runs.diagnosisExplanation')}</p><p>{t('runs.diagnosisRemedy')}</p><pre>[09:42:04] unresolved: libexample.so.1</pre><button class="text-button" on:click={() => navigate('recipes',selected.pkg)}>{t('runs.reviewFailure')} →</button></div>{/if}{/if}
<div class="detail-buttons">{#if selected.status==='validated'}<button class="button primary" on:click={() => openModal('publish')}>{t('runs.publish')}</button><button class="button secondary" on:click={() => openModal('validate')}>{t('runs.revalidate')}</button>{:else if selected.status==='running'||selected.status==='queued'}<button class="button secondary" on:click={() => openModal('cancel')}>{t('runs.cancel')}</button>{:else if selected.status==='completed'||selected.status==='prepared'}<button class="button primary" on:click={() => openModal('validate')}>{t('runs.validate')}</button>{/if}</div></section>
<section class="panel"><div class="section-head"><h2>{t('runs.stages')}</h2>{#if selected.status==='running'}<StatusChip label={t('runs.active',{stage:formatCount(locale,4),total:formatCount(locale,8)})} tone="info" icon="◌" />{/if}</div><div class="stage-list">{#each stageKeys as key,index}<div class:stage-current={stageState(selected,index)==='running'} class:stage-failed={stageState(selected,index)==='failed'}><span class="stage-number">{stageState(selected,index)==='failed'?'!':stageState(selected,index)==='running'?'◌':stageState(selected,index)==='completed'?'✓':index+1}</span><strong>{t(key)}</strong><small>{t('common.'+stageState(selected,index))}</small></div>{/each}</div></section>
<section class="panel"><details class="dependency-details"><summary><span><strong>{t(selected.status==='failed'?'runs.dependenciesReview':'runs.dependenciesResolved')}</strong><small>{selected.status==='failed'?countMessage(locale,'runs.unresolved.one','runs.unresolved.other',1):t('runs.effective')+': libc6, libssl3'}</small></span><span>⌄</span></summary><div class="dependency-grid"><div><span>{t('runs.detected')}</span><strong>libc6, libssl3</strong></div><div><span>{t('runs.manual')}</span><strong>ca-certificates</strong></div><div><span>{t('runs.bundled')}</span><strong>{t('common.none')}</strong></div><div><span>{t('runs.overrides')}</span><strong>{t('common.none')}</strong></div><div><span>{t('runs.unresolved')}</span><strong>{selected.status==='failed'?'libexample.so.1':t('common.none')}</strong></div><div><span>{t('runs.effective')}</span><strong>libc6, libssl3, ca-certificates</strong></div></div></details></section>
<section class="panel"><div class="section-head"><h2>{t('runs.logs')}</h2><details class="log-options"><summary>{t('runs.logOptions')}</summary><label class="log-verbosity">{t('runs.verbosity')} <select bind:value={verbosity}>{#each ['compact','normal','verbose','raw'] as level}<option value={level}>{t('runs.verbosity.'+level)}</option>{/each}</select></label></details></div>{#if selected.status==='running'}<div class="log-follow"><span role="status">{t(following?'runs.following':'runs.paused')}</span><button class="text-button" on:click={() => following=!following}>{t(following?'runs.pause':'runs.resume')}</button></div>{/if}<pre class="log-output">[09:42:02] {selected.id}
[09:42:03] source: {selected.pkg}
[09:42:04] status: {selected.status}{#if verbosity==='verbose'||verbosity==='raw'}
[09:42:05] dependency scan: libc6, libssl3{/if}{#if verbosity==='raw'}
{'\u001b[32mraw process output\u001b[0m'}{/if}</pre><RunPoller scenario={selected.status==='running'?'running':'normal'} /></section></div>{/if}</div>
