<script>
  import {tick} from 'svelte';
  import {translate,localeNames} from '../lib/i18n.js';
  export let locale,theme,changeTheme,changeLocale,openModal;
  $: t=(key,values={})=>translate(locale,key,values);
  let tab='general';
  let tabBar;
  const tabs=['general','repository','github','auth','notifications','automation','advanced'];
  const initial={appName:'DebBuilder',publicUrl:'https://packages.example.org',repoUrl:'https://repo.probatou.com',suite:'Luminous',component:'main',arch:'amd64',githubToken:'',issuer:'https://id.example.org',clientId:'debbuilder',redirect:'https://packages.example.org/auth/callback',clientSecret:'',ntfyServer:'https://ntfy.example.org',topic:'debbuilder',ntfyToken:'',autoValidate:true,autoPublish:false,cleanupEnabled:true,failedRetain:5};
  let saved={...initial};
  let draft={...initial};
  let errors={};
  let secretConfigured={githubToken:true,clientSecret:true,ntfyToken:true};
  $: dirty=JSON.stringify(draft)!==JSON.stringify(saved);
  const definitions={general:[['appName','settings.appName','text',true],['publicUrl','settings.publicUrl','url',false]],repository:[['repoUrl','settings.repoUrl','url',true],['suite','settings.suite','text',true],['component','settings.component','text',true],['arch','settings.arch','architecture',true]],github:[['githubToken','settings.githubToken','secret',false]],auth:[['issuer','settings.issuer','url',false],['clientId','settings.clientId','text',false],['redirect','settings.redirect','url',false],['clientSecret','settings.clientSecret','secret',false]],notifications:[['ntfyServer','settings.ntfyServer','url',false],['topic','settings.topic','text',false],['ntfyToken','settings.ntfyToken','secret',false]],automation:[['autoValidate','settings.autoValidate','boolean',false],['autoPublish','settings.autoPublish','boolean',false]],advanced:[['cleanupEnabled','settings.cleanupEnabled','boolean',false],['failedRetain','system.failedRetain','number',true]]};
  async function selectTab(key){tab=key;await tick();if(tabBar?.scrollWidth>tabBar?.clientWidth){const item=tabBar.querySelector('[aria-current=page]');if(item){const left=item.offsetLeft-tabBar.offsetLeft;const right=left+item.offsetWidth;if(left<tabBar.scrollLeft)tabBar.scrollLeft=left;else if(right>tabBar.scrollLeft+tabBar.clientWidth)tabBar.scrollLeft=right-tabBar.clientWidth;}}}
  function edit(key,value){draft={...draft,[key]:value};errors={...errors,[key]:''};}
  function validate(){const next={};for(const [section,items] of Object.entries(definitions))for(const [key,,type,required] of items){const value=String(draft[key]??'').trim();if(required&&!value)next[key]=t('editor.required');else if(type==='number'&&(!Number.isInteger(Number(value))||Number(value)<0||Number(value)>1000))next[key]=t('editor.numericRange');else if(type==='url'&&value){try{const url=new URL(value);if(!['http:','https:'].includes(url.protocol))next[key]=t('editor.invalidUrl');}catch{next[key]=t('editor.invalidUrl');}}}if(draft.autoPublish&&!draft.autoValidate)next.autoPublish=t('settings.autoPublishRequiresValidate');errors=next;return !Object.keys(next).length;}
  function save(){if(!validate()){const first=Object.keys(errors)[0];selectTab(Object.keys(definitions).find(section=>definitions[section].some(([key])=>key===first))||tab);return;}const next={...draft};for(const key of ['githubToken','clientSecret','ntfyToken']){if(next[key])secretConfigured={...secretConfigured,[key]:true};next[key]='';}saved=next;draft={...next};errors={};}
  function cancel(){draft={...saved};errors={};}
</script>
<div class="settings-layout"><nav bind:this={tabBar} class="settings-nav" aria-label={t('nav.settings')}>{#each tabs as key}<button class:active={tab===key} aria-current={tab===key?'page':undefined} on:click={() => selectTab(key)}>{t('settings.'+key)}</button>{/each}</nav><div class="settings-content">
{#if tab==='general'}<section class="panel"><h2>{t('settings.appearance')}</h2><div class="field-grid"><label><span>{t('settings.theme')}</span><select value={theme} on:change={(event)=>changeTheme(event.currentTarget.value)}><option value="system">{t('settings.themeSystem')}</option><option value="light">{t('settings.themeLight')}</option><option value="dark">{t('settings.themeDark')}</option></select></label><label><span>{t('settings.language')}</span><select value={locale} on:change={(event)=>changeLocale(event.currentTarget.value)}>{#each Object.entries(localeNames) as [code,name]}<option value={code}>{name}</option>{/each}</select></label></div><p class="field-help">{t('settings.localHelp')}</p></section>{/if}
<section class="panel"><div class="section-head"><h2>{t('settings.'+tab)}</h2></div><div class="settings-edit-fields">{#each definitions[tab] as [key,label,type,required]}<label class="settings-edit-field"><span>{t(label)}{required?' *':''}</span>{#if type==='boolean'}<input type="checkbox" checked={draft[key]} on:change={(event)=>edit(key,event.currentTarget.checked)} />{:else if type==='architecture'}<select value={draft[key]} on:change={(event)=>edit(key,event.currentTarget.value)}>{#each ['amd64','arm64','armhf','i386','all'] as arch}<option value={arch}>{arch}</option>{/each}</select>{:else}<input type={type==='secret'?'password':type==='url'?'url':type==='number'?'number':'text'} min={type==='number'?'0':undefined} max={type==='number'?'1000':undefined} value={draft[key]} autocomplete="off" aria-invalid={!!errors[key]} on:input={(event)=>edit(key,event.currentTarget.value)} />{/if}{#if type==='secret'}<small>{secretConfigured[key]?t('editor.configured'):t('editor.notConfigured')} · {t('settings.secretHelp')}</small>{/if}{#if errors[key]}<small class="field-error" role="alert">{errors[key]}</small>{/if}</label>{/each}</div>{#if tab==='auth'}<p class="field-help">{t('settings.authMode')}</p>{/if}{#if tab==='notifications'}<button class="button secondary" on:click={() => openModal('notification')}>{t('settings.testNotification')}</button>{/if}</section>
<div class="panel settings-savebar"><strong class:dirty>{t(dirty?'editor.unsaved':'editor.saved')}</strong><p class="muted">{t('editor.localFixture')}</p><div><button class="button secondary" disabled={!dirty} on:click={cancel}>{t('editor.cancel')}</button><button class="button primary" disabled={!dirty} on:click={save}>{t('editor.save')}</button></div></div></div></div>
