<script>
  import {tick} from 'svelte';
  import {translate,formatWhen} from '../lib/i18n.js';
  import StatusChip from '../lib/StatusChip.svelte';
  import RecipeRows from '../lib/RecipeRows.svelte';
  export let locale,scenario,openModal;
  $: t=(key,values={})=>translate(locale,key,values);
  let tab='health';
  let tabBar;
  async function selectTab(key){tab=key;await tick();if(tabBar?.scrollWidth>tabBar?.clientWidth){const item=tabBar.querySelector('[aria-current=page]');if(item){const left=item.offsetLeft-tabBar.offsetLeft;const right=left+item.offsetWidth;if(left<tabBar.scrollLeft)tabBar.scrollLeft=left;else if(right>tabBar.scrollLeft+tabBar.clientWidth)tabBar.scrollLeft=right-tabBar.clientWidth;}}}
  let managedSaved={active:true,maintainer:'DebBuilder maintainers',environment:[],inactivityTimeout:300,maximumRuntime:'',limits:{memory:'',tasks:'',cpu:'',ioRead:'',ioWrite:''}};
  let managedDraft=structuredClone(managedSaved);
  $: managedChanged=JSON.stringify(managedDraft)!==JSON.stringify(managedSaved);
  const envFields=[{key:'key',label:'recipeUx.variable'},{key:'value',label:'recipeUx.value'}];
  $: recovery=scenario==='recovery';
  const health=[['system.runtime','DebBuilder v1.0.0'],['system.admission','1 / 2'],['system.containment','systemd · cgroup v2'],['system.tooling','dpkg-deb · apt'],['system.validation','system.validationFixture'],['system.automation','system.automationFixture']];
</script>
<div bind:this={tabBar} class="segmented-tabs" aria-label={t('nav.system')}>{#each ['health','maintenance','developer','selfBuild'] as key}<button class:active={tab===key} aria-current={tab===key?'page':undefined} on:click={() => selectTab(key)}>{t('system.'+key)}</button>{/each}</div>
{#if tab==='health'}{#if recovery}<div class="attention-notice"><span class="notice-mark">!</span><div><strong>{t('runs.recoveryTitle')}</strong><p>{t('runs.recoveryHelp')}</p></div></div>{/if}<div class="system-grid"><section class="panel"><div class="section-head"><h2>{t('system.diagnostics')}</h2><StatusChip label={t(recovery?'common.needsReview':'status.systemHealthy')} tone={recovery?'warning':'success'} icon={recovery?'!':'✓'} /></div><div class="diagnostic-list">{#each health as [key,value]}<div><span>{t(key)}</span><strong>{value.startsWith('system.')?t(value):value}</strong><StatusChip label={t(key==='system.validation'?'common.unknown':recovery&&key==='system.admission'?'common.blocked':'common.available')} tone={key==='system.validation'?'neutral':recovery&&key==='system.admission'?'warning':'success'} icon={key==='system.validation'?'?':'●'} /></div>{/each}</div></section><aside class="panel compact-panel"><h2>{t('system.selfBuild')}</h2><p class="muted">{t('system.selfBuildHelp')}</p><div class="repo-line">debbuilder · 1.0.0</div><StatusChip label={t('recipes.managed')} tone="neutral" icon="◇" /><button class="button secondary" on:click={() => selectTab('selfBuild')}>{t('system.selfBuild')} →</button></aside></div><section class="panel health-repository"><div class="section-head"><h2>{t('system.repository')}</h2><StatusChip label={t('common.online')} tone="success" icon="●" /></div><div class="detail-facts"><div><span>{t('system.repositoryHealth')}</span><strong>{t('common.available')}</strong></div><div><span>{t('system.signingStatus')}</span><strong>{t('common.available')}</strong></div><div><span>{t('system.metadataAvailability')}</span><strong>InRelease</strong></div><div><span>{t('repository.last')}</span><strong>{formatWhen(locale,'2026-09-25T09:42:00Z')}</strong></div></div></section>
{:else if tab==='maintenance'}<div class="maintenance-layout"><section class="panel maintenance-card"><h2>{t('system.storage')}</h2><div class="maintenance-facts"><div><span>{t('system.history')}</span><strong>{t('system.runCount',{count:128})}</strong></div><div><span>{t('system.retention')}</span><strong>{t('system.retentionFixture')}</strong></div></div></section><section class="panel maintenance-card"><h2>{t('system.cleanup')}</h2><div class="maintenance-facts"><div><span>{t('system.cleanup')}</span><strong>{t('common.available')}</strong></div><div><span>{t('system.failedRetain')}</span><strong>5</strong></div></div><button class="button secondary" on:click={() => openModal('clear')}>{t('system.clear')}</button></section><section class="panel maintenance-card"><h2>{t('system.recovery')}</h2><p class="muted">{t('system.recoveryHelp')}</p><StatusChip label={t(recovery?'common.blocked':'common.ready')} tone={recovery?'danger':'success'} icon={recovery?'!':'✓'} /></section></div>
{:else if tab==='developer'}<div class="system-grid"><section class="panel"><h2>{t('system.developer')}</h2><div class="developer-list"><button on:click={() => openModal('inspectors')}>{t('system.inspectors')} <span>→</span></button><button on:click={() => openModal('bundle')}>{t('system.bundle')} <span>→</span></button><button on:click={() => openModal('openapi')}>{t('system.openapi')} <span>→</span></button></div></section><aside class="panel compact-panel"><h2>{t('system.schemas')}</h2><p class="muted">{t('system.developerHelp')}</p></aside></div>{:else}<div class="managed-self-build"><section class="panel"><div class="section-head"><div><h2>{t('system.selfBuild')}</h2><p class="muted">{t('system.selfBuildHelp')}</p></div><StatusChip label={t('recipes.managed')} tone="neutral" icon="◇" /></div><div class="plan-rows"><div><span>{t('recipes.planSource')}</span><strong>ProBatou/DebBuilder · GitHub</strong></div><div><span>{t('recipes.planBuild')}</span><strong>{t('recipeUx.sourceBuild')}</strong></div><div><span>{t('recipes.planInstall')}</span><strong>/opt/debbuilder</strong></div><div><span>{t('recipes.planService')}</span><strong>debbuilder.service</strong></div></div><p class="recipe-context">{t('recipeUx.managedReadOnly')}</p></section><section class="panel recipe-section"><h3>{t('recipeUx.managedOverrides')}</h3><div class="recipe-form-grid"><label class="recipe-check"><input type="checkbox" bind:checked={managedDraft.active} />{t('recipeUx.active')}</label><label>{t('recipeUx.maintainer')}<input bind:value={managedDraft.maintainer} /></label><label>{t('recipeUx.inactivitySeconds')}<input type="number" min="1" max="86400" bind:value={managedDraft.inactivityTimeout} /></label><label>{t('recipeUx.maximumSeconds')}<input type="number" min="1" max="604800" bind:value={managedDraft.maximumRuntime} /></label></div><RecipeRows {locale} title={t('recipes.environment')} bind:rows={managedDraft.environment} fields={envFields} /><h3>{t('recipes.limits')}</h3><p class="recipe-context">{t('recipeUx.inheritedLimits')}</p><div class="recipe-form-grid"><label>{t('recipeUx.memoryBytes')}<input type="number" min="1" bind:value={managedDraft.limits.memory} /></label><label>{t('recipeUx.tasks')}<input type="number" min="1" bind:value={managedDraft.limits.tasks} /></label><label>{t('recipeUx.cpuPercent')}<input type="number" min="1" bind:value={managedDraft.limits.cpu} /></label><label>{t('recipeUx.ioRead')}<input type="number" min="1" bind:value={managedDraft.limits.ioRead} /></label><label>{t('recipeUx.ioWrite')}<input type="number" min="1" bind:value={managedDraft.limits.ioWrite} /></label></div>{#if managedChanged}<div class="recipe-savebar"><strong>{t('editor.unsaved')}</strong><div><button class="button secondary" on:click={() => managedDraft=structuredClone(managedSaved)}>{t('editor.cancel')}</button><button class="button primary" on:click={() => managedSaved=structuredClone(managedDraft)}>{t('editor.save')}</button></div></div>{/if}</section></div>{/if}
