<script>
  import {translate,formatWhen} from '../lib/i18n.js';
  import StatusChip from '../lib/StatusChip.svelte';
  export let locale,scenario,openModal;
  $: t=(key,values={})=>translate(locale,key,values);
  let tab='health';
  $: recovery=scenario==='recovery';
  const health=[['system.runtime','DebBuilder v1.0.0'],['system.admission','1 / 2'],['system.containment','systemd · cgroup v2'],['system.tooling','dpkg-deb · apt'],['system.validation','system.validationFixture'],['system.automation','system.automationFixture']];
</script>
<div class="segmented-tabs" aria-label={t('nav.system')}>{#each ['health','maintenance','developer'] as key}<button class:active={tab===key} aria-current={tab===key?'page':undefined} on:click={() => tab=key}>{t('system.'+key)}</button>{/each}</div>
{#if tab==='health'}{#if recovery}<div class="attention-notice"><span class="notice-mark">!</span><div><strong>{t('runs.recoveryTitle')}</strong><p>{t('runs.recoveryHelp')}</p></div></div>{/if}<div class="system-grid"><section class="panel"><div class="section-head"><h2>{t('system.diagnostics')}</h2><StatusChip label={t(recovery?'common.needsReview':'status.systemHealthy')} tone={recovery?'warning':'success'} icon={recovery?'!':'✓'} /></div><div class="diagnostic-list">{#each health as [key,value]}<div><span>{t(key)}</span><strong>{value.startsWith('system.')?t(value):value}</strong><StatusChip label={t(key==='system.validation'?'common.unknown':recovery&&key==='system.admission'?'common.blocked':'common.available')} tone={key==='system.validation'?'neutral':recovery&&key==='system.admission'?'warning':'success'} icon={key==='system.validation'?'?':'●'} /></div>{/each}</div></section><aside class="panel compact-panel"><h2>{t('system.selfBuild')}</h2><p class="muted">{t('system.selfBuildHelp')}</p><div class="repo-line">debbuilder · 1.0.0</div><StatusChip label={t('recipes.managed')} tone="neutral" icon="◇" /></aside></div><section class="panel health-repository"><div class="section-head"><h2>{t('system.repository')}</h2><StatusChip label={t('common.online')} tone="success" icon="●" /></div><div class="detail-facts"><div><span>{t('system.repositoryHealth')}</span><strong>{t('common.available')}</strong></div><div><span>{t('system.signingStatus')}</span><strong>{t('common.available')}</strong></div><div><span>{t('system.metadataAvailability')}</span><strong>InRelease</strong></div><div><span>{t('repository.last')}</span><strong>{formatWhen(locale,'2026-09-25T09:42:00Z')}</strong></div></div></section>
{:else if tab==='maintenance'}<div class="system-grid"><section class="panel"><h2>{t('system.storage')}</h2><div class="detail-facts"><div><span>{t('system.history')}</span><strong>{t('system.runCount',{count:128})}</strong></div><div><span>{t('system.retention')}</span><strong>{t('system.retentionFixture')}</strong></div><div><span>{t('system.cleanup')}</span><strong>{t('common.available')}</strong></div><div><span>{t('system.failedRetain')}</span><strong>5</strong></div></div><div class="detail-buttons"><button class="button secondary" on:click={() => openModal('clear')}>{t('system.clear')}</button></div></section><aside class="panel compact-panel"><h2>{t('system.recovery')}</h2><p class="muted">{t('system.recoveryHelp')}</p><StatusChip label={t(recovery?'common.blocked':'common.ready')} tone={recovery?'danger':'success'} icon={recovery?'!':'✓'} /></aside></div>
{:else}<div class="system-grid"><section class="panel"><h2>{t('system.developer')}</h2><div class="developer-list"><button on:click={() => openModal('inspectors')}>{t('system.inspectors')} <span>→</span></button><button on:click={() => openModal('bundle')}>{t('system.bundle')} <span>→</span></button><button on:click={() => openModal('openapi')}>{t('system.openapi')} <span>→</span></button></div></section><aside class="panel compact-panel"><h2>{t('system.schemas')}</h2><p class="muted">{t('system.developerHelp')}</p></aside></div>{/if}
