<script>
  import {onMount} from 'svelte';
  import {api} from '../api/client.js';
  import {navigate} from '../navigation/location.js';
  import {openRecipe} from '../navigation/recipe.js';
  import {t,number} from '../i18n/i18n.js';
  import ErrorNotice from '../components/ErrorNotice.svelte';
  import Status from '../components/Status.svelte';
  export let id = '', language = 'en';
  let rows = [], selected = null, error = null, detailError = null, query = '', filter = 'all', controller, detailController, revision = 0;
  let inventoryOpen = false, inventory = null, inventoryError = null, inventoryLoading = false, inventoryQuery = '', inventoryController, inventoryRevision = 0, navigationError = null;
  async function loadInventory() {inventoryController?.abort(); inventoryController = new AbortController(); const token = ++inventoryRevision; inventoryLoading = true; inventoryError = null; inventory = null; try {const result = await api.inventory({signal:inventoryController.signal}); if(token === inventoryRevision) inventory = result;} catch(caught) {if(caught.name !== 'AbortError' && token === inventoryRevision) inventoryError = caught;} finally {if(token === inventoryRevision) inventoryLoading = false;}}
  function toggleInventory() {inventoryOpen = !inventoryOpen; if(inventoryOpen && !inventory) loadInventory();}
  async function review(recipeId) {navigationError = null; try {await openRecipe(recipeId);} catch(caught) {navigationError = caught;}}
  async function load() {controller?.abort(); controller = new AbortController(); error = null; try {rows = (await api.packages({signal:controller.signal})).packages || [];} catch (caught) {if(caught.name !== 'AbortError') error = caught;}}
  async function detail(name) {detailController?.abort(); detailController = new AbortController(); const token = ++revision; detailError = null; selected = null; if (!name) return; try {const value = (await api.package(name,{signal:detailController.signal})).package; if(token === revision) selected = value;} catch(caught) {if(caught.name !== 'AbortError' && token === revision) detailError = caught;}}
  onMount(() => {load(); return () => {controller?.abort(); detailController?.abort(); inventoryController?.abort();};});
  $: detail(id || rows[0]?.name);
  $: filtered = rows.filter(row => row.name?.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || (row.lifecycle_display_status || row.lifecycle_state || row.status) === filter));
  $: statuses = [...new Set(rows.map(row => row.lifecycle_display_status || row.lifecycle_state || row.status).filter(Boolean))];
  $: inventoryRows = (inventory?.packages || []).filter(row => `${row.name} ${row.version} ${row.architecture} ${row.component}`.toLowerCase().includes(inventoryQuery.toLowerCase()));
</script>
<ErrorNotice {error} retry={load} {language}/>
{#if inventoryOpen}
  <div class="inventory-view"><button class="back-button" onclick={toggleInventory}>← {t('back',language)}</button><section class="panel"><p class="muted">{t('packages',language)} / {t('repositoryInventory',language)}</p><div class="section-head"><h2>{t('repositoryInventory',language)}</h2></div><p class="muted">{t('inventoryDistinction',language)}</p><ErrorNotice error={inventoryError} retry={loadInventory} {language}/>{#if inventoryLoading}<p>{t('loading',language)}</p>{:else if inventory}<div class="repo-facts"><div><span>{t('suite',language)}</span><strong>{inventory.repository?.suite || '—'}</strong></div><div><span>{t('components',language)}</span><strong>{inventory.repository?.components?.join(', ') || '—'}</strong></div><div><span>{t('architectures',language)}</span><strong>{inventory.repository?.architectures?.join(', ') || '—'}</strong></div><div><span>{t('publishedEntries',language)}</span><strong>{number(inventory.packages?.length,language)}</strong></div></div>{/if}</section>
  {#if inventory}<section class="panel"><div class="section-head"><h2>{t('publishedEntries',language)}</h2><small>{inventoryRows.length} / {inventory.packages?.length || 0}</small></div><label>{t('search',language)} <input type="search" bind:value={inventoryQuery}></label>{#if inventoryRows.length}<div class="table-wrap"><table><thead><tr><th>{t('packages',language)}</th><th>{t('version',language)}</th><th>{t('architecture',language)}</th><th>{t('component',language)}</th></tr></thead><tbody>{#each inventoryRows as item}<tr><td>{item.name}</td><td>{item.version}</td><td>{item.architecture}</td><td>{item.component}</td></tr>{/each}</tbody></table></div>{:else}<p>{t('noItems',language)}</p>{/if}</section>{/if}</div>
{:else}
  <div class="split package-layout"><section class="panel package-list"><div class="section-head"><h2>{t('packages',language)}</h2><small>{filtered.length} / {rows.length}</small></div><div class="filters"><label>{t('search',language)}<input type="search" bind:value={query}></label><label>{t('status',language)}<select bind:value={filter}><option value="all">{t('all',language)}</option>{#each statuses as state}<option value={state}>{state}</option>{/each}</select></label></div><div class="package-columns list-head"><span>{t('packages',language)}</span><span>{t('status',language)}</span><span>{t('built',language)}</span><span>{t('published',language)}</span></div><div class="list">{#each filtered as row (row.name)}<button class:active={(id || rows[0]?.name) === row.name} class="row package-columns" onclick={() => navigate('packages',row.name)}><span><strong>{row.name}</strong><small>{row.source?.repository || row.source?.type || ''}</small></span><Status value={row.lifecycle_display_status || row.lifecycle_state || row.status} {language}/><span class="version-cell">{row.version?.candidate || '—'}</span><span class="version-cell">{row.version?.published || row.apt_version || '—'}</span></button>{:else}<p class="empty-state">{t('noItems',language)}</p>{/each}</div></section>
  <div class="detail package-detail-wrap">{#if id}<button class="back" onclick={() => navigate('packages')}>← {t('back',language)}</button>{/if}<ErrorNotice error={detailError} retry={() => detail(id || rows[0]?.name)} {language}/>{#if selected}<section class="panel package-detail"><p class="muted">{t('packages',language)} / <strong>{selected.name}</strong></p><h2>{selected.name}</h2><p class="muted">{selected.source?.type || selected.source?.repository || ''}</p><dl><dt>{t('source',language)}</dt><dd>{selected.source?.repository || selected.source?.type || '—'}</dd><dt>{t('built',language)}</dt><dd>{selected.version?.candidate || '—'}</dd><dt>{t('published',language)}</dt><dd>{selected.version?.published || selected.apt_version || '—'}</dd><dt>{t('status',language)}</dt><dd><Status value={selected.lifecycle_display_status || selected.lifecycle_state || selected.status} {language}/></dd></dl><div class="detail-buttons">{#if selected.build?.latest_run_id}<button onclick={() => navigate('runs',selected.build.latest_run_id)}>{t('viewRun',language)} →</button>{/if}{#if selected.recipe}<button onclick={() => review(selected.recipe)}>{t('reviewRecipe',language)} →</button>{/if}</div><ErrorNotice error={navigationError} {language}/></section>{:else if (id || rows.length) && !detailError}<p>{t('loading',language)}</p>{/if}</div></div>
  <section class="panel repository-summary"><div><h2>{t('repository',language)}</h2><p class="muted">{t('inventoryDistinction',language)}</p></div><button onclick={toggleInventory}>{t('viewInventory',language)} →</button></section>
{/if}
