<script>
  import {onMount} from 'svelte';
  import {api} from '../api/client.js';
  import {navigate} from '../navigation/location.js';
  import {openRecipe} from '../navigation/recipe.js';
  import {t,number} from '../i18n/i18n.js';
  import ErrorNotice from '../components/ErrorNotice.svelte';
  import Status from '../components/Status.svelte';
  export let id = '', language = 'en';
  let rows = [], selected = null, error = null, detailError = null, query = '', controller, detailController, revision = 0;
  let inventoryOpen = false, inventory = null, inventoryError = null, inventoryLoading = false, inventoryQuery = '', inventoryController, inventoryRevision = 0, navigationError = null;
  async function loadInventory() {inventoryController?.abort(); inventoryController = new AbortController(); const token = ++inventoryRevision; inventoryLoading = true; inventoryError = null; inventory = null; try {const result = await api.inventory({signal:inventoryController.signal}); if(token === inventoryRevision) inventory = result;} catch(caught) {if(caught.name !== 'AbortError' && token === inventoryRevision) inventoryError = caught;} finally {if(token === inventoryRevision) inventoryLoading = false;}}
  function toggleInventory() {inventoryOpen = !inventoryOpen; if(inventoryOpen && !inventory) loadInventory();}
  async function review(recipeId) {navigationError = null; try {await openRecipe(recipeId);} catch(caught) {navigationError = caught;}}
  async function load() {controller?.abort(); controller = new AbortController(); error = null; try {rows = (await api.packages({signal:controller.signal})).packages || [];} catch (caught) {if(caught.name !== 'AbortError') error = caught;}}
  async function detail(name) {detailController?.abort(); detailController = new AbortController(); const token = ++revision; detailError = null; selected = null; if (!name) return; try {const value = (await api.package(name,{signal:detailController.signal})).package; if(token === revision) selected = value;} catch(caught) {if(caught.name !== 'AbortError' && token === revision) detailError = caught;}}
  onMount(() => {load(); return () => {controller?.abort(); detailController?.abort(); inventoryController?.abort();};});
  $: detail(id);
  $: filtered = rows.filter(row => row.name?.toLowerCase().includes(query.toLowerCase()));
  $: inventoryRows = (inventory?.packages || []).filter(row => `${row.name} ${row.version} ${row.architecture} ${row.component}`.toLowerCase().includes(inventoryQuery.toLowerCase()));
</script>
<h1>{t('packages',language)}</h1><ErrorNotice {error} retry={load} {language}/>
<div class="split"><section class="panel"><label>{t('search',language)} <input type="search" bind:value={query}></label><div class="list">{#each filtered as row (row.name)}<button class:active={id===row.name} class="row" onclick={() => navigate('packages',row.name)}><span><strong>{row.name}</strong><small>{row.version?.published || row.apt_version || '—'}</small></span><Status value={row.lifecycle_display_status || row.lifecycle_state || row.status} {language}/></button>{:else}<p>{t('noItems',language)}</p>{/each}</div></section>
<div class="detail">{#if id}<button class="back" onclick={() => navigate('packages')}>← {t('back',language)}</button>{/if}<ErrorNotice error={detailError} retry={() => detail(id)} {language}/>{#if selected}<section class="panel"><h2>{selected.name}</h2><Status value={selected.lifecycle_display_status || selected.lifecycle_state || selected.status} {language}/><dl><dt>{t('published',language)}</dt><dd>{selected.version?.published || selected.apt_version || '—'}</dd><dt>{t('built',language)}</dt><dd>{selected.version?.candidate || '—'}</dd><dt>{t('source',language)}</dt><dd>{selected.source?.repository || selected.source?.type || '—'}</dd><dt>{t('repository',language)}</dt><dd>{selected.repository?.url || '—'}</dd></dl>{#if selected.build?.latest_run_id}<button onclick={() => navigate('runs',selected.build.latest_run_id)}>{t('viewRun',language)} →</button>{/if}{#if selected.recipe}<p><button onclick={() => review(selected.recipe)}>{t('reviewRecipe',language)} →</button></p><ErrorNotice error={navigationError} {language}/>{/if}</section>{:else if id && !detailError}<p>{t('loading',language)}</p>{:else}<p>{t('noPackage',language)}</p>{/if}</div></div>
<section class="panel"><div class="section-head"><h2>{t('repositoryInventory',language)}</h2><button onclick={toggleInventory}>{inventoryOpen ? t('close',language) : t('viewInventory',language)}</button></div><p class="muted">{t('inventoryDistinction',language)}</p>{#if inventoryOpen}<ErrorNotice error={inventoryError} retry={loadInventory} {language}/>{#if inventoryLoading}<p>{t('loading',language)}</p>{:else if inventory}<dl><dt>{t('suite',language)}</dt><dd>{inventory.repository?.suite}</dd><dt>{t('components',language)}</dt><dd>{inventory.repository?.components?.join(', ')}</dd><dt>{t('architectures',language)}</dt><dd>{inventory.repository?.architectures?.join(', ')}</dd><dt>{t('publishedEntries',language)}</dt><dd>{number(inventory.packages?.length,language)}</dd></dl><label>{t('search',language)} <input type="search" bind:value={inventoryQuery}></label>{#if inventoryRows.length}<div class="table-wrap"><table><thead><tr><th>{t('packages',language)}</th><th>{t('version',language)}</th><th>{t('architecture',language)}</th><th>{t('component',language)}</th></tr></thead><tbody>{#each inventoryRows as item}<tr><td>{item.name}</td><td>{item.version}</td><td>{item.architecture}</td><td>{item.component}</td></tr>{/each}</tbody></table></div>{:else}<p>{t('noItems',language)}</p>{/if}{/if}{/if}</section>
