import {writable} from 'svelte/store';

export const locale = writable('en');
const key = 'debBuilder24Locale';
const translations = {
  en: {menu:'Menu',started:'Started',overview:'Overview',packages:'Packages',runs:'Runs',system:'System',recipes:'Recipes',settings:'Settings',availableLater:'Available in a later migration',loading:'Loading…',retry:'Retry',search:'Search',all:'All',status:'Status',details:'Details',back:'Back',open:'Open',viewRun:'View Run',reviewRecipe:'Review Recipe',needsAttention:'Needs attention',activeWork:'Active work',readyToValidate:'Ready to validate',recentRuns:'Recent Runs',repository:'Repository',health:'Health',developer:'Developer',maintenance:'Maintenance',unavailable:'Unavailable',noItems:'No items',published:'Published',built:'Built',source:'Source',stages:'Stages',diagnosis:'Diagnosis',dependencies:'Dependencies',logs:'Logs',follow:'Follow',pause:'Pause',options:'Options',compact:'Compact',normal:'Normal',verbose:'Verbose',raw:'Raw',unknown:'Unknown',version:'Version',theme:'Theme',language:'Language',systemTheme:'System',light:'Light',dark:'Dark',signedMetadata:'Signed metadata',notExposed:'Exact repository inventory is not exposed by the current API.',openapi:'OpenAPI contract',forbidden:'Access forbidden',signIn:'Sign in',authRequired:'Authentication required',refresh:'Refresh',noRun:'Select a Run',noPackage:'Select a Package',runtime:'Runtime',recovery:'Recovery',automation:'Automation',overviewSubtitle:"Needs attention, active work and recent activity.",packagesSubtitle:"Manage package versions and published artifacts.",recipesSubtitle:"Choose a Recipe and review its effective plan.",runsSubtitle:"Select a Run to inspect progress and next actions.",systemSubtitle:"DebBuilder health, host capability and operational tools.",settingsSubtitle:"Configure application defaults and integrations.",appearance:"Appearance",localPreferences:"Theme and language are stored only in this browser.",testBuildHelp:"Test checks this draft without packaging; Build produces a package version. Neither saves the Recipe."},
  fr: {menu:'Menu',started:'Début',overview:'Vue d’ensemble',packages:'Paquets',runs:'Exécutions',system:'Système',recipes:'Recettes',settings:'Paramètres',availableLater:'Disponible lors d’une migration ultérieure',loading:'Chargement…',retry:'Réessayer',search:'Rechercher',all:'Tous',status:'État',details:'Détails',back:'Retour',open:'Ouvrir',viewRun:'Voir l’exécution',reviewRecipe:'Voir la recette',needsAttention:'À traiter',activeWork:'Travail actif',readyToValidate:'Prêt à valider',recentRuns:'Exécutions récentes',repository:'Dépôt',health:'Santé',developer:'Développeur',maintenance:'Maintenance',unavailable:'Indisponible',noItems:'Aucun élément',published:'Publié',built:'Construit',source:'Source',stages:'Étapes',diagnosis:'Diagnostic',dependencies:'Dépendances',logs:'Journaux',follow:'Suivre',pause:'Pause',options:'Options',compact:'Compact',normal:'Normal',verbose:'Détaillé',raw:'Brut',unknown:'Inconnu',version:'Version',theme:'Thème',language:'Langue',systemTheme:'Système',light:'Clair',dark:'Sombre',signedMetadata:'Métadonnées signées',notExposed:'L’inventaire exact du dépôt n’est pas exposé par l’API actuelle.',openapi:'Contrat OpenAPI',forbidden:'Accès interdit',signIn:'Se connecter',authRequired:'Authentification requise',refresh:'Actualiser',noRun:'Choisir une exécution',noPackage:'Choisir un paquet',runtime:'Exécution',recovery:'Récupération',automation:'Automatisation',overviewSubtitle:"Actions nécessaires, travaux actifs et activité récente.",packagesSubtitle:"Gérez les versions et artefacts publiés.",recipesSubtitle:"Choisissez une recette et examinez son plan effectif.",runsSubtitle:"Choisissez une exécution pour voir sa progression et ses actions.",systemSubtitle:"État de DebBuilder, capacités de l’hôte et outils opérationnels.",settingsSubtitle:"Configurez les valeurs par défaut et les intégrations.",appearance:"Apparence",localPreferences:"Le thème et la langue sont enregistrés uniquement dans ce navigateur.",testBuildHelp:"Tester vérifie ce brouillon sans construire ; Construire produit une version du paquet. Aucune de ces actions n’enregistre la recette."},
  de: {menu:'Menü',started:'Beginn',overview:'Übersicht',packages:'Pakete',runs:'Läufe',system:'System',recipes:'Rezepte',settings:'Einstellungen',availableLater:'In einer späteren Migration verfügbar',loading:'Lädt…',retry:'Erneut versuchen',search:'Suchen',all:'Alle',status:'Status',details:'Details',back:'Zurück',open:'Öffnen',viewRun:'Lauf anzeigen',reviewRecipe:'Rezept anzeigen',needsAttention:'Handlungsbedarf',activeWork:'Aktive Arbeit',readyToValidate:'Bereit zur Validierung',recentRuns:'Letzte Läufe',repository:'Repository',health:'Zustand',developer:'Entwickler',maintenance:'Wartung',unavailable:'Nicht verfügbar',noItems:'Keine Einträge',published:'Veröffentlicht',built:'Gebaut',source:'Quelle',stages:'Phasen',diagnosis:'Diagnose',dependencies:'Abhängigkeiten',logs:'Protokolle',follow:'Folgen',pause:'Pause',options:'Optionen',compact:'Kompakt',normal:'Normal',verbose:'Ausführlich',raw:'Roh',unknown:'Unbekannt',version:'Version',theme:'Design',language:'Sprache',systemTheme:'System',light:'Hell',dark:'Dunkel',signedMetadata:'Signierte Metadaten',notExposed:'Das genaue Repository-Inventar wird von der aktuellen API nicht bereitgestellt.',openapi:'OpenAPI-Vertrag',forbidden:'Zugriff verweigert',signIn:'Anmelden',authRequired:'Anmeldung erforderlich',refresh:'Aktualisieren',noRun:'Lauf auswählen',noPackage:'Paket auswählen',runtime:'Laufzeit',recovery:'Wiederherstellung',automation:'Automatisierung',overviewSubtitle:"Handlungsbedarf, aktive Arbeit und letzte Aktivitäten.",packagesSubtitle:"Paketversionen und veröffentlichte Artefakte verwalten.",recipesSubtitle:"Rezept auswählen und den wirksamen Plan prüfen.",runsSubtitle:"Ausführung auswählen, um Fortschritt und Aktionen zu prüfen.",systemSubtitle:"DebBuilder-Status, Host-Funktionen und Betriebswerkzeuge.",settingsSubtitle:"Anwendungsstandards und Integrationen konfigurieren.",appearance:"Darstellung",localPreferences:"Design und Sprache werden nur in diesem Browser gespeichert.",testBuildHelp:"Test prüft diesen Entwurf ohne Paketbau; Build erzeugt eine Paketversion. Beides speichert das Rezept nicht."},
  es: {menu:'Menú',started:'Inicio',overview:'Resumen',packages:'Paquetes',runs:'Ejecuciones',system:'Sistema',recipes:'Recetas',settings:'Ajustes',availableLater:'Disponible en una migración posterior',loading:'Cargando…',retry:'Reintentar',search:'Buscar',all:'Todos',status:'Estado',details:'Detalles',back:'Volver',open:'Abrir',viewRun:'Ver ejecución',reviewRecipe:'Ver receta',needsAttention:'Requiere atención',activeWork:'Trabajo activo',readyToValidate:'Listo para validar',recentRuns:'Ejecuciones recientes',repository:'Repositorio',health:'Salud',developer:'Desarrollo',maintenance:'Mantenimiento',unavailable:'No disponible',noItems:'Sin elementos',published:'Publicado',built:'Compilado',source:'Origen',stages:'Etapas',diagnosis:'Diagnóstico',dependencies:'Dependencias',logs:'Registros',follow:'Seguir',pause:'Pausar',options:'Opciones',compact:'Compacto',normal:'Normal',verbose:'Detallado',raw:'Sin procesar',unknown:'Desconocido',version:'Versión',theme:'Tema',language:'Idioma',systemTheme:'Sistema',light:'Claro',dark:'Oscuro',signedMetadata:'Metadatos firmados',notExposed:'La API actual no expone el inventario exacto del repositorio.',openapi:'Contrato OpenAPI',forbidden:'Acceso prohibido',signIn:'Iniciar sesión',authRequired:'Autenticación requerida',refresh:'Actualizar',noRun:'Selecciona una ejecución',noPackage:'Selecciona un paquete',runtime:'Entorno',recovery:'Recuperación',automation:'Automatización',overviewSubtitle:"Atención, trabajo activo y actividad reciente.",packagesSubtitle:"Gestione versiones y artefactos publicados.",recipesSubtitle:"Elija una receta y revise su plan efectivo.",runsSubtitle:"Seleccione una ejecución para ver su progreso y acciones.",systemSubtitle:"Estado de DebBuilder, capacidades del host y herramientas operativas.",settingsSubtitle:"Configure los valores e integraciones de la aplicación.",appearance:"Apariencia",localPreferences:"El tema y el idioma se guardan solo en este navegador.",testBuildHelp:"Probar comprueba este borrador sin compilar; Compilar genera una versión del paquete. Ninguna de estas acciones guarda la receta."},
};
const extra = {
  en: {menu:'Menu',detected:'detected',bundled:'bundled',unresolved:'unresolved',overrides:'Overrides',depends:'Depends',inspectors:'inspectors',supportBundle:'support bundle',readOnly:'Read-only',verbosity:'Log detail',runId:'Run ID',recipeFact:'Recipe',runMode:'Run mode',finished:'Finished',duration:'Duration',sourceRef:'Source reference',artifactFact:'Artifact',failureStage:'Failed stage',remediation:'Next action',technicalFacts:'Technical facts',errorDetail:'Error detail',moreChecks:'More checks',managedStorage:'Managed storage',inspectDiagnosticPayload:'Inspect diagnostic payload',available:'Available',recipeSchema:'Recipe schema',detectedProject:'Detected project',automationPolicy:'Policy',currentState:'Current state',lastCheck:'Last check',copy:'Copy',entries:'entries',structuredChange:'Structured change',copied:'Copied',customizeGroupHelp:'Common changes for this task.',advancedGroupHelp:'Less frequent operational settings.',expertGroupHelp:'Specialized configuration; change only when needed.',configuredValue:'Configured',notConfiguredValue:'Not configured',enabledValue:'Enabled',disabledValue:'Disabled',active:'Active',inactive:'Inactive',plan:'Plan',effectivePackagePlan:'Effective package plan',nextStep:'Next step',noMatchingEvidence:'No matching current evidence',testRequired:'Test required',sourceBuild:'Source build',prebuilt:'Prebuilt artifact',buildCommands:'build commands',serviceNotConfigured:'Service not configured',elfOverrides:'Existing ELF overrides',inspection:'Inspection',advanced:'Advanced configuration',advancedTab:'Advanced',canonicalJson:'View canonical JSON',invalidRecipes:'Invalid stored Recipes',selectRecipe:'Select a Recipe',repositoryInventory:'Repository inventory',viewInventory:'View repository inventory',close:'Close',inventoryDistinction:'Exact reprepro entries; DebBuilder Packages are a separate managed view.',suite:'Suite',components:'Components',architectures:'Architectures',publishedEntries:'Published entries',architecture:'Architecture',component:'Component',managedSelfBuild:'System-managed self-build',managedIdentity:'Managed identity',definitionVersion:'Definition version',allowedOverrides:'Allowed operator overrides',currentOverrides:'Current overrides',Configured:'Configured',Default:'Default','Unknown / pending':'Unknown / pending','Not applicable':'Not applicable'},
  fr: {menu:'Menu',detected:'détectées',bundled:'intégrées',unresolved:'non résolues',overrides:'Substitutions',depends:'Dépendances',inspectors:'inspecteurs',supportBundle:'archive de support',readOnly:'Lecture seule',verbosity:'Détail du journal',runId:'ID de l’exécution',recipeFact:'Recette',runMode:'Mode d’exécution',finished:'Terminé',duration:'Durée',sourceRef:'Référence source',artifactFact:'Artéfact',failureStage:'Étape en échec',remediation:'Action suivante',technicalFacts:'Faits techniques',errorDetail:'Détail de l’erreur',moreChecks:'Autres vérifications',managedStorage:'Stockage géré',inspectDiagnosticPayload:'Examiner les diagnostics bruts',available:'Disponible',recipeSchema:'Schéma de recette',detectedProject:'Projet détecté',automationPolicy:'Politique',currentState:'État actuel',lastCheck:'Dernière vérification',copy:'Copier',entries:'entrées',structuredChange:'Changement structuré',copied:'Copié',customizeGroupHelp:'Changements courants pour cette tâche.',advancedGroupHelp:'Paramètres opérationnels moins fréquents.',expertGroupHelp:'Configuration spécialisée à modifier si nécessaire.',configuredValue:'Configuré',notConfiguredValue:'Non configuré',enabledValue:'Activé',disabledValue:'Désactivé',active:'Active',inactive:'Inactive',plan:'Plan',effectivePackagePlan:'Plan de paquet effectif',nextStep:'Étape suivante',noMatchingEvidence:'Aucune preuve actuelle correspondante',testRequired:'Test requis',sourceBuild:'Construction depuis les sources',prebuilt:'Artéfact précompilé',buildCommands:'commandes de construction',serviceNotConfigured:'Service non configuré',elfOverrides:'Substitutions ELF existantes',inspection:'Inspection',advanced:'Configuration avancée',advancedTab:'Avancé',canonicalJson:'Voir le JSON canonique',invalidRecipes:'Recettes stockées invalides',selectRecipe:'Choisir une recette',repositoryInventory:'Inventaire du dépôt',viewInventory:'Voir l’inventaire du dépôt',close:'Fermer',inventoryDistinction:'Entrées reprepro exactes ; les paquets DebBuilder sont une vue gérée distincte.',suite:'Suite',components:'Composants',architectures:'Architectures',publishedEntries:'Entrées publiées',architecture:'Architecture',component:'Composant',managedSelfBuild:'Auto-construction gérée par le système',managedIdentity:'Identité gérée',definitionVersion:'Version de définition',allowedOverrides:'Substitutions autorisées',currentOverrides:'Substitutions actuelles',Configured:'Configuré',Default:'Par défaut','Unknown / pending':'Inconnu / en attente','Not applicable':'Sans objet'},
  de: {menu:'Menü',detected:'erkannt',bundled:'enthalten',unresolved:'ungelöst',overrides:'Überschreibungen',depends:'Abhängigkeiten',inspectors:'Inspektoren',supportBundle:'Supportpaket',readOnly:'Schreibgeschützt',verbosity:'Protokolldetail',runId:'Run-ID',recipeFact:'Rezept',runMode:'Ausführungsmodus',finished:'Beendet',duration:'Dauer',sourceRef:'Quellreferenz',artifactFact:'Artefakt',failureStage:'Fehlgeschlagene Phase',remediation:'Nächster Schritt',technicalFacts:'Technische Angaben',errorDetail:'Fehlerdetails',moreChecks:'Weitere Prüfungen',managedStorage:'Verwalteter Speicher',inspectDiagnosticPayload:'Diagnosedaten anzeigen',available:'Verfügbar',recipeSchema:'Rezeptschema',detectedProject:'Erkanntes Projekt',automationPolicy:'Richtlinie',currentState:'Aktueller Zustand',lastCheck:'Letzte Prüfung',copy:'Kopieren',entries:'Einträge',structuredChange:'Strukturierte Änderung',copied:'Kopiert',customizeGroupHelp:'Häufige Änderungen für diese Aufgabe.',advancedGroupHelp:'Seltener benötigte Betriebseinstellungen.',expertGroupHelp:'Spezialkonfiguration nur bei Bedarf ändern.',configuredValue:'Konfiguriert',notConfiguredValue:'Nicht konfiguriert',enabledValue:'Aktiviert',disabledValue:'Deaktiviert',active:'Aktiv',inactive:'Inaktiv',plan:'Plan',effectivePackagePlan:'Effektiver Paketplan',nextStep:'Nächster Schritt',noMatchingEvidence:'Kein passender aktueller Nachweis',testRequired:'Test erforderlich',sourceBuild:'Quellcodebau',prebuilt:'Vorgefertigtes Artefakt',buildCommands:'Build-Befehle',serviceNotConfigured:'Dienst nicht konfiguriert',elfOverrides:'Vorhandene ELF-Ausnahmen',inspection:'Inspektion',advanced:'Erweiterte Konfiguration',advancedTab:'Erweitert',canonicalJson:'Kanonisches JSON anzeigen',invalidRecipes:'Ungültige gespeicherte Rezepte',selectRecipe:'Rezept auswählen',repositoryInventory:'Repository-Inventar',viewInventory:'Repository-Inventar anzeigen',close:'Schließen',inventoryDistinction:'Exakte reprepro-Einträge; DebBuilder-Pakete sind eine getrennte verwaltete Ansicht.',suite:'Suite',components:'Komponenten',architectures:'Architekturen',publishedEntries:'Veröffentlichte Einträge',architecture:'Architektur',component:'Komponente',managedSelfBuild:'Systemverwalteter Selbstbau',managedIdentity:'Verwaltete Identität',definitionVersion:'Definitionsversion',allowedOverrides:'Erlaubte Anpassungen',currentOverrides:'Aktuelle Anpassungen',Configured:'Konfiguriert',Default:'Standard','Unknown / pending':'Unbekannt / ausstehend','Not applicable':'Nicht anwendbar'},
  es: {menu:'Menú',detected:'detectadas',bundled:'incluidas',unresolved:'sin resolver',overrides:'Sustituciones',depends:'Dependencias',inspectors:'inspectores',supportBundle:'paquete de soporte',readOnly:'Solo lectura',verbosity:'Detalle del registro',runId:'ID de ejecución',recipeFact:'Receta',runMode:'Modo de ejecución',finished:'Finalizado',duration:'Duración',sourceRef:'Referencia de origen',artifactFact:'Artefacto',failureStage:'Etapa fallida',remediation:'Próxima acción',technicalFacts:'Datos técnicos',errorDetail:'Detalle del error',moreChecks:'Más comprobaciones',managedStorage:'Almacenamiento gestionado',inspectDiagnosticPayload:'Inspeccionar diagnóstico',available:'Disponible',recipeSchema:'Esquema de receta',detectedProject:'Proyecto detectado',automationPolicy:'Política',currentState:'Estado actual',lastCheck:'Última comprobación',copy:'Copiar',entries:'entradas',structuredChange:'Cambio estructurado',copied:'Copiado',customizeGroupHelp:'Cambios habituales para esta tarea.',advancedGroupHelp:'Ajustes operativos menos frecuentes.',expertGroupHelp:'Configuración especializada solo cuando sea necesaria.',configuredValue:'Configurado',notConfiguredValue:'Sin configurar',enabledValue:'Activado',disabledValue:'Desactivado',active:'Activa',inactive:'Inactiva',plan:'Plan',effectivePackagePlan:'Plan efectivo del paquete',nextStep:'Siguiente paso',noMatchingEvidence:'Sin evidencia actual coincidente',testRequired:'Se requiere prueba',sourceBuild:'Compilación desde código',prebuilt:'Artefacto precompilado',buildCommands:'comandos de compilación',serviceNotConfigured:'Servicio no configurado',elfOverrides:'Excepciones ELF existentes',inspection:'Inspección',advanced:'Configuración avanzada',advancedTab:'Avanzado',canonicalJson:'Ver JSON canónico',invalidRecipes:'Recetas almacenadas no válidas',selectRecipe:'Seleccionar una receta',repositoryInventory:'Inventario del repositorio',viewInventory:'Ver inventario del repositorio',close:'Cerrar',inventoryDistinction:'Entradas exactas de reprepro; los paquetes DebBuilder son una vista gestionada separada.',suite:'Suite',components:'Componentes',architectures:'Arquitecturas',publishedEntries:'Entradas publicadas',architecture:'Arquitectura',component:'Componente',managedSelfBuild:'Autocompilación gestionada por el sistema',managedIdentity:'Identidad gestionada',definitionVersion:'Versión de definición',allowedOverrides:'Cambios permitidos',currentOverrides:'Cambios actuales',Configured:'Configurado',Default:'Predeterminado','Unknown / pending':'Desconocido / pendiente','Not applicable':'No aplicable'},
};
const editorChrome = {
  en: {view:'View',edit:'Edit',editing:'Editing',unsaved:'Unsaved changes',validate:'Validate',validating:'Validating…',validated:'Changes valid',cancel:'Cancel',customize:'Customize',expert:'Expert',reviewChanges:'Review changes',noChanges:'No changes',loadedBaseline:'Saved',currentDraft:'Your changes',discardChanges:'Discard changes?',unsavedChanges:'Your Recipe draft has unsaved changes.',keepEditing:'Keep editing',discard:'Discard draft',add:'Add',remove:'Remove',move:'Move',up:'up',down:'down',key:'Key',value:'Value'},
  fr: {view:'Voir',edit:'Modifier',editing:'Modification',unsaved:'Modifications non enregistrées',validate:'Valider',validating:'Validation…',validated:'Modifications valides',cancel:'Annuler',customize:'Personnaliser',expert:'Expert',reviewChanges:'Vérifier les changements',noChanges:'Aucun changement',loadedBaseline:'Enregistré',currentDraft:'Vos modifications',discardChanges:'Abandonner les modifications ?',unsavedChanges:'Le brouillon de la recette contient des modifications non enregistrées.',keepEditing:'Continuer',discard:'Abandonner',add:'Ajouter',remove:'Supprimer',move:'Déplacer',up:'vers le haut',down:'vers le bas',key:'Clé',value:'Valeur'},
  de: {view:'Ansehen',edit:'Bearbeiten',editing:'Bearbeitung',unsaved:'Ungespeicherte Änderungen',validate:'Validieren',validating:'Validierung…',validated:'Änderungen gültig',cancel:'Abbrechen',customize:'Anpassen',expert:'Experte',reviewChanges:'Änderungen prüfen',noChanges:'Keine Änderungen',loadedBaseline:'Gespeichert',currentDraft:'Ihre Änderungen',discardChanges:'Änderungen verwerfen?',unsavedChanges:'Der Rezeptentwurf enthält ungespeicherte Änderungen.',keepEditing:'Weiter bearbeiten',discard:'Verwerfen',add:'Hinzufügen',remove:'Entfernen',move:'Verschieben',up:'nach oben',down:'nach unten',key:'Schlüssel',value:'Wert'},
  es: {view:'Ver',edit:'Editar',editing:'Edición',unsaved:'Cambios sin guardar',validate:'Validar',validating:'Validando…',validated:'Cambios válidos',cancel:'Cancelar',customize:'Personalizar',expert:'Experto',reviewChanges:'Revisar cambios',noChanges:'Sin cambios',loadedBaseline:'Guardado',currentDraft:'Tus cambios',discardChanges:'¿Descartar cambios?',unsavedChanges:'El borrador de la receta contiene cambios sin guardar.',keepEditing:'Seguir editando',discard:'Descartar',add:'Añadir',remove:'Quitar',move:'Mover',up:'arriba',down:'abajo',key:'Clave',value:'Valor'},
};
const recipeJsonChrome = {
  en: {jsonEdit:'Edit JSON',jsonImport:'Import JSON file',jsonExport:'Export JSON',jsonApply:'Apply to draft',jsonDiscard:'Discard JSON edits',jsonEditorLabel:'Recipe JSON',jsonPending:'Apply the JSON to continue',jsonHelp:'The Recipe ID must stay the same. Apply to update the draft, then save separately.',jsonTooLarge:'JSON must be smaller than 2 MB.',jsonImportError:'The JSON file could not be read.',jsonSyntaxError:'Invalid JSON',jsonObjectRequired:'The JSON must contain a Recipe object.',jsonIdentityError:'The Recipe ID must match the selected Recipe.',jsonDraftChanged:'The draft changed since the JSON editor opened. Discard these JSON edits and try again.'},
  fr: {jsonEdit:'Modifier le JSON',jsonImport:'Importer un fichier JSON',jsonExport:'Exporter le JSON',jsonApply:'Appliquer au brouillon',jsonDiscard:'Annuler l’édition JSON',jsonEditorLabel:'JSON de la recette',jsonPending:'Appliquez le JSON pour continuer',jsonHelp:'L’identifiant de la recette doit rester identique. Appliquez au brouillon, puis enregistrez.',jsonTooLarge:'Le JSON doit faire moins de 2 Mo.',jsonImportError:'Impossible de lire le fichier JSON.',jsonSyntaxError:'JSON invalide',jsonObjectRequired:'Le JSON doit contenir un objet recette.',jsonIdentityError:'L’identifiant doit correspondre à la recette sélectionnée.',jsonDraftChanged:'Le brouillon a changé depuis l’ouverture de l’éditeur JSON. Annulez cette édition et réessayez.'},
  de: {jsonEdit:'JSON bearbeiten',jsonImport:'JSON-Datei importieren',jsonExport:'JSON exportieren',jsonApply:'Auf Entwurf anwenden',jsonDiscard:'JSON-Änderungen verwerfen',jsonEditorLabel:'Rezept-JSON',jsonPending:'JSON anwenden, um fortzufahren',jsonHelp:'Die Rezept-ID muss gleich bleiben. Auf den Entwurf anwenden und dann separat speichern.',jsonTooLarge:'JSON darf höchstens 2 MB groß sein.',jsonImportError:'Die JSON-Datei konnte nicht gelesen werden.',jsonSyntaxError:'Ungültiges JSON',jsonObjectRequired:'Das JSON muss ein Rezeptobjekt enthalten.',jsonIdentityError:'Die Rezept-ID muss zum ausgewählten Rezept passen.',jsonDraftChanged:'Der Entwurf wurde seit dem Öffnen des JSON-Editors geändert. Verwerfen Sie die JSON-Änderungen und versuchen Sie es erneut.'},
  es: {jsonEdit:'Editar JSON',jsonImport:'Importar archivo JSON',jsonExport:'Exportar JSON',jsonApply:'Aplicar al borrador',jsonDiscard:'Descartar edición JSON',jsonEditorLabel:'JSON de la receta',jsonPending:'Aplica el JSON para continuar',jsonHelp:'El ID de la receta debe seguir igual. Aplica los cambios al borrador y luego guarda.',jsonTooLarge:'El JSON debe ocupar menos de 2 MB.',jsonImportError:'No se pudo leer el archivo JSON.',jsonSyntaxError:'JSON no válido',jsonObjectRequired:'El JSON debe contener un objeto de receta.',jsonIdentityError:'El ID debe coincidir con la receta seleccionada.',jsonDraftChanged:'El borrador cambió desde que se abrió el editor JSON. Descarta estos cambios e inténtalo de nuevo.'},
};
const recipeValidationChrome = {
  en: {recipeValidationIssue:'Recipe validation',serviceRequiresDetails:'To enable the service, enter its name and command.',serviceNameInvalid:'Enter a valid service name ending in .service (for example, my-app.service).',serviceNameSuffixHint:'The .service suffix is added automatically.',serviceDisabledKeepsDetails:'Disabling keeps the service name and command in this Recipe.'},
  fr: {recipeValidationIssue:'Validation de la recette',serviceRequiresDetails:'Pour activer le service, renseignez son nom et sa commande.',serviceNameInvalid:'Saisissez un nom de service valide terminé par .service (par exemple, mon-app.service).',serviceNameSuffixHint:'Le suffixe .service est ajouté automatiquement.',serviceDisabledKeepsDetails:'La désactivation conserve le nom et la commande du service dans cette recette.'},
  de: {recipeValidationIssue:'Rezeptvalidierung',serviceRequiresDetails:'Geben Sie zum Aktivieren des Dienstes seinen Namen und Befehl ein.',serviceNameInvalid:'Geben Sie einen gültigen Dienstnamen mit der Endung .service ein (z. B. meine-app.service).',serviceNameSuffixHint:'Die Endung .service wird automatisch ergänzt.',serviceDisabledKeepsDetails:'Beim Deaktivieren bleiben Dienstname und Befehl in diesem Rezept erhalten.'},
  es: {recipeValidationIssue:'Validación de la receta',serviceRequiresDetails:'Para activar el servicio, indique su nombre y comando.',serviceNameInvalid:'Indique un nombre de servicio válido que termine en .service (por ejemplo, mi-app.service).',serviceNameSuffixHint:'El sufijo .service se añade automáticamente.',serviceDisabledKeepsDetails:'Al desactivar el servicio se conservan su nombre y comando en esta receta.'},
};
const planLabels = {
  fr: {'Source':'Source','Tracking':'Suivi','Ref':'Référence','Version policy':'Politique de version','Artifact mode':'Mode d’artéfact','Build strategy':'Stratégie de construction','Package':'Paquet','Architecture':'Architecture','Output':'Sortie','Install destination':'Destination','Install content':'Contenu installé','Installation strategy':'Stratégie d’installation','Service':'Service','Ownership':'Propriétaire','Account':'Compte','Runtime Depends':'Dépendances d’exécution','ELF detection':'Détection ELF','Automation':'Automatisation','Resources':'Ressources','Lifecycle hooks':'Scripts de cycle de vie'},
  de: {'Source':'Quelle','Tracking':'Nachverfolgung','Ref':'Referenz','Version policy':'Versionsregel','Artifact mode':'Artefaktmodus','Build strategy':'Build-Strategie','Package':'Paket','Architecture':'Architektur','Output':'Ausgabe','Install destination':'Installationsziel','Install content':'Installationsinhalt','Installation strategy':'Installationsstrategie','Service':'Dienst','Ownership':'Eigentümer','Account':'Konto','Runtime Depends':'Laufzeitabhängigkeiten','ELF detection':'ELF-Erkennung','Automation':'Automatisierung','Resources':'Ressourcen','Lifecycle hooks':'Lebenszyklus-Skripte'},
  es: {'Source':'Origen','Tracking':'Seguimiento','Ref':'Referencia','Version policy':'Política de versión','Artifact mode':'Modo de artefacto','Build strategy':'Estrategia de compilación','Package':'Paquete','Architecture':'Arquitectura','Output':'Salida','Install destination':'Destino de instalación','Install content':'Contenido instalado','Installation strategy':'Estrategia de instalación','Service':'Servicio','Ownership':'Propietario','Account':'Cuenta','Runtime Depends':'Dependencias de ejecución','ELF detection':'Detección ELF','Automation':'Automatización','Resources':'Recursos','Lifecycle hooks':'Scripts de ciclo de vida'},
};
const persistenceChrome = {
  en: {save:'Save',saving:'Saving…',saved:'Recipe saved',newRecipe:'New Recipe',recipeId:'Recipe ID',githubRepository:'GitHub repository',continue:'Continue',recipeConflict:'Recipe conflict',conflictPreserved:'This Recipe changed on the server. Your unsaved changes were preserved.',recipeAlreadyExists:'Recipe already exists',latestServer:'Latest server version',changedBoth:'Changed on both sides',changedLocally:'Changed only locally',changedServer:'Changed only on server',discardReload:'Discard my draft and reload',changeIdentity:'Change Recipe ID',revisionUnavailable:'Recipe revision unavailable. Reload before saving.'},
  fr: {save:'Enregistrer',saving:'Enregistrement…',saved:'Recette enregistrée',newRecipe:'Nouvelle recette',recipeId:'Identifiant de recette',githubRepository:'Dépôt GitHub',continue:'Continuer',recipeConflict:'Conflit de recette',conflictPreserved:'Cette recette a changé sur le serveur. Vos modifications ont été conservées.',recipeAlreadyExists:'La recette existe déjà',latestServer:'Dernière version serveur',changedBoth:'Modifié des deux côtés',changedLocally:'Modifié localement uniquement',changedServer:'Modifié sur le serveur uniquement',discardReload:'Abandonner mon brouillon et recharger',changeIdentity:'Changer l’identifiant',revisionUnavailable:'Révision indisponible. Rechargez avant d’enregistrer.'},
  de: {save:'Speichern',saving:'Speichert…',saved:'Rezept gespeichert',newRecipe:'Neues Rezept',recipeId:'Rezept-ID',githubRepository:'GitHub-Repository',continue:'Weiter',recipeConflict:'Rezeptkonflikt',conflictPreserved:'Dieses Rezept wurde auf dem Server geändert. Ihre Änderungen wurden behalten.',recipeAlreadyExists:'Rezept existiert bereits',latestServer:'Neueste Serverversion',changedBoth:'Auf beiden Seiten geändert',changedLocally:'Nur lokal geändert',changedServer:'Nur auf dem Server geändert',discardReload:'Entwurf verwerfen und neu laden',changeIdentity:'Rezept-ID ändern',revisionUnavailable:'Revision fehlt. Vor dem Speichern neu laden.'},
  es: {save:'Guardar',saving:'Guardando…',saved:'Receta guardada',newRecipe:'Nueva receta',recipeId:'ID de receta',githubRepository:'Repositorio GitHub',continue:'Continuar',recipeConflict:'Conflicto de receta',conflictPreserved:'Esta receta cambió en el servidor. Se conservaron sus cambios.',recipeAlreadyExists:'La receta ya existe',latestServer:'Última versión del servidor',changedBoth:'Cambiado en ambos lados',changedLocally:'Cambiado solo localmente',changedServer:'Cambiado solo en el servidor',discardReload:'Descartar borrador y recargar',changeIdentity:'Cambiar ID de receta',revisionUnavailable:'Falta la revisión. Recargue antes de guardar.'},
};
const runChrome = {
  en: {test:'Test',buildAction:'Build',startingTest:'Starting Test…',startingBuild:'Starting Build…',testHelp:'Test resolves and inspects this draft, applies source changes in an isolated workspace, and previews staging without running build commands or creating a package.',testHelpPrebuilt:'Test resolves this draft and previews applicable packaging steps without producing a package.',buildHelp:'Build runs this draft to produce a package. Configured server automation may start validation and publication afterward.',buildHelpPrebuilt:'Build acquires or packages the selected upstream artifact. Configured server automation may start validation and publication afterward.',saveBeforeRun:'Save the Recipe once before running it.',enableBeforeRun:'Enable this Recipe before running it.',testQueued:'Test queued',buildQueued:'Build queued',runNotStarted:'Run admission not confirmed',admissionUnknown:'The admission result is unknown. Check Runs before trying again.',viewRuns:'View Runs'},
  fr: {test:'Tester',buildAction:'Construire',startingTest:'Lancement du test…',startingBuild:'Lancement de la construction…',testHelp:'Le test résout et inspecte ce brouillon, applique les changements de source dans un espace isolé et prévisualise la préparation sans exécuter les commandes de construction ni créer de paquet.',testHelpPrebuilt:'Le test résout ce brouillon et prévisualise les étapes de préparation applicables sans produire de paquet.',buildHelp:'La construction utilise ce brouillon pour produire un paquet. L’automatisation configurée sur le serveur peut ensuite lancer la validation et la publication.',buildHelpPrebuilt:'La construction acquiert ou prépare l’artéfact amont sélectionné. L’automatisation configurée sur le serveur peut ensuite lancer la validation et la publication.',saveBeforeRun:'Enregistrez la recette une fois avant de la lancer.',enableBeforeRun:'Activez cette recette avant de la lancer.',testQueued:'Test en attente',buildQueued:'Construction en attente',runNotStarted:'Admission non confirmée',admissionUnknown:'Le résultat de l’admission est inconnu. Vérifiez les exécutions avant de réessayer.',viewRuns:'Voir les exécutions'},
  de: {test:'Testen',buildAction:'Bauen',startingTest:'Test wird gestartet…',startingBuild:'Build wird gestartet…',testHelp:'Der Test löst diesen Entwurf auf, prüft ihn, wendet Quelländerungen in einem isolierten Arbeitsbereich an und zeigt die Paketvorbereitung an, ohne Build-Befehle auszuführen oder ein Paket zu erstellen.',testHelpPrebuilt:'Der Test löst diesen Entwurf auf und zeigt anwendbare Vorbereitungsschritte an, ohne ein Paket zu erstellen.',buildHelp:'Der Build erstellt aus diesem Entwurf ein Paket. Die konfigurierte Serverautomatisierung kann danach Validierung und Veröffentlichung starten.',buildHelpPrebuilt:'Der Build übernimmt oder verpackt das gewählte Upstream-Artefakt. Die konfigurierte Serverautomatisierung kann danach Validierung und Veröffentlichung starten.',saveBeforeRun:'Speichern Sie das Rezept einmal, bevor Sie es ausführen.',enableBeforeRun:'Aktivieren Sie dieses Rezept vor dem Start.',testQueued:'Test eingereiht',buildQueued:'Build eingereiht',runNotStarted:'Run-Zulassung nicht bestätigt',admissionUnknown:'Das Zulassungsergebnis ist unbekannt. Prüfen Sie die Läufe vor einem erneuten Versuch.',viewRuns:'Läufe anzeigen'},
  es: {test:'Probar',buildAction:'Construir',startingTest:'Iniciando prueba…',startingBuild:'Iniciando compilación…',testHelp:'La prueba resuelve e inspecciona este borrador, aplica cambios de origen en un espacio aislado y previsualiza la preparación sin ejecutar comandos de compilación ni crear un paquete.',testHelpPrebuilt:'La prueba resuelve este borrador y previsualiza los pasos de preparación aplicables sin producir un paquete.',buildHelp:'La compilación usa este borrador para producir un paquete. La automatización configurada en el servidor puede iniciar después la validación y la publicación.',buildHelpPrebuilt:'La compilación obtiene o empaqueta el artefacto de origen seleccionado. La automatización configurada en el servidor puede iniciar después la validación y la publicación.',saveBeforeRun:'Guarda la receta una vez antes de ejecutarla.',enableBeforeRun:'Activa esta receta antes de ejecutarla.',testQueued:'Prueba en cola',buildQueued:'Compilación en cola',runNotStarted:'Admisión sin confirmar',admissionUnknown:'Se desconoce el resultado de la admisión. Revisa las ejecuciones antes de reintentar.',viewRuns:'Ver ejecuciones'},
};
const overviewChrome = {
  en: {overviewFailureAction:'Diagnostic & logs',overviewViewPackage:'View package',overviewUpdateAction:'View update',overviewValidationAction:'Validate package',overviewPublicationAction:'Publish package',overviewCheckingAction:'Checking…',overviewFollowRun:'Follow Run',overviewViewPackages:'View packages',overviewViewSystem:'View system',overviewValidationInfo:'Start artifact validation for this Build Run. Configured automation may publish it after validation succeeds.',overviewPublicationInfo:'Publish this validated artifact to the APT repository.',overviewActionUnavailable:'This action is no longer available for the latest Build Run. Review the current package or Run.',overviewConfirmPublication:'I confirm publication of this exact package and version to APT.',overviewStartValidation:'Start validation',overviewPublishToApt:'Publish to APT',overviewActionWorking:'Working…',overviewValidationStarted:'Validation started. View the Run to follow its progress.',overviewPublicationDone:'Publication succeeded. The package overview is refreshing.'},
  fr: {overviewFailureAction:'Diagnostic et journaux',overviewViewPackage:'Voir le paquet',overviewUpdateAction:'Voir la mise à jour',overviewValidationAction:'Valider le paquet',overviewPublicationAction:'Publier le paquet',overviewCheckingAction:'Vérification…',overviewFollowRun:'Suivre l’exécution',overviewViewPackages:'Voir les paquets',overviewViewSystem:'Voir le système',overviewValidationInfo:'Lancez la validation de l’artéfact de cette construction. L’automatisation configurée peut le publier après une validation réussie.',overviewPublicationInfo:'Publiez cet artéfact validé dans le dépôt APT.',overviewActionUnavailable:'Cette action n’est plus disponible pour la dernière construction. Consultez le paquet ou l’exécution actuelle.',overviewConfirmPublication:'Je confirme la publication de ce paquet et de cette version exacts dans APT.',overviewStartValidation:'Lancer la validation',overviewPublishToApt:'Publier dans APT',overviewActionWorking:'En cours…',overviewValidationStarted:'Validation lancée. Consultez l’exécution pour suivre sa progression.',overviewPublicationDone:'Publication réussie. La vue d’ensemble se met à jour.'},
  de: {overviewFailureAction:'Diagnose und Protokolle',overviewViewPackage:'Paket anzeigen',overviewUpdateAction:'Update anzeigen',overviewValidationAction:'Paket validieren',overviewPublicationAction:'Paket veröffentlichen',overviewCheckingAction:'Prüfung…',overviewFollowRun:'Lauf verfolgen',overviewViewPackages:'Pakete anzeigen',overviewViewSystem:'System anzeigen',overviewValidationInfo:'Artefaktvalidierung für diesen Build-Lauf starten. Die konfigurierte Automatisierung kann es nach erfolgreicher Validierung veröffentlichen.',overviewPublicationInfo:'Dieses validierte Artefakt im APT-Repository veröffentlichen.',overviewActionUnavailable:'Diese Aktion ist für den neuesten Build-Lauf nicht mehr verfügbar. Prüfen Sie das aktuelle Paket oder den Lauf.',overviewConfirmPublication:'Ich bestätige die Veröffentlichung dieses Pakets und genau dieser Version in APT.',overviewStartValidation:'Validierung starten',overviewPublishToApt:'In APT veröffentlichen',overviewActionWorking:'Wird ausgeführt…',overviewValidationStarted:'Validierung gestartet. Im Lauf können Sie den Fortschritt verfolgen.',overviewPublicationDone:'Veröffentlichung erfolgreich. Die Übersicht wird aktualisiert.'},
  es: {overviewFailureAction:'Diagnóstico y registros',overviewViewPackage:'Ver paquete',overviewUpdateAction:'Ver actualización',overviewValidationAction:'Validar paquete',overviewPublicationAction:'Publicar paquete',overviewCheckingAction:'Comprobando…',overviewFollowRun:'Seguir ejecución',overviewViewPackages:'Ver paquetes',overviewViewSystem:'Ver sistema',overviewValidationInfo:'Inicia la validación del artefacto de esta compilación. La automatización configurada puede publicarlo después de una validación correcta.',overviewPublicationInfo:'Publica este artefacto validado en el repositorio APT.',overviewActionUnavailable:'Esta acción ya no está disponible para la última compilación. Revisa el paquete o la ejecución actual.',overviewConfirmPublication:'Confirmo la publicación de este paquete y esta versión exactos en APT.',overviewStartValidation:'Iniciar validación',overviewPublishToApt:'Publicar en APT',overviewActionWorking:'En curso…',overviewValidationStarted:'Validación iniciada. Consulta la ejecución para seguir el progreso.',overviewPublicationDone:'Publicación correcta. La vista general se está actualizando.'},
};
const packageChrome = {
  en: {packageNextFailure:'This step failed. Inspect the Run diagnosis and logs before trying again.',packageNextActive:'Work is in progress. Follow its Run.',packageNextValidation:'The build artifact is ready for validation.',packageNextPublication:'Validation succeeded. Confirm publication to the APT repository.',packageNextUnavailable:'This action is unavailable for the current Build Run. Inspect the Run for details.',packageNextBuild:'A build is needed. Open the Recipe to review it and start Build.',packageNextNoRecipe:'No Recipe is linked to this package.',packageNextCurrent:'No action is required. You can review the Recipe or Build Run.',packageNextRun:'A Build Run is available to inspect.',packageNextRecipe:'Review the Recipe to continue.',packageViewLogs:'View diagnosis and logs',packageOpenRecipeToBuild:'Open Recipe to Build',packageValidationStarted:'Validation started. Follow the Run to see its progress.',packagePublicationDone:'Publication succeeded. The package details are updating.'},
  fr: {packageNextFailure:'Cette étape a échoué. Consultez le diagnostic et les journaux de l’exécution avant de réessayer.',packageNextActive:'Un travail est en cours. Suivez son exécution.',packageNextValidation:'L’artéfact construit est prêt à être validé.',packageNextPublication:'La validation a réussi. Confirmez la publication dans le dépôt APT.',packageNextUnavailable:'Cette action est indisponible pour la construction actuelle. Consultez l’exécution pour en savoir plus.',packageNextBuild:'Une construction est nécessaire. Ouvrez la recette pour la vérifier et lancer la construction.',packageNextNoRecipe:'Aucune recette n’est liée à ce paquet.',packageNextCurrent:'Aucune action nécessaire. Vous pouvez consulter la recette ou la construction.',packageNextRun:'Une construction est disponible à consulter.',packageNextRecipe:'Consultez la recette pour continuer.',packageViewLogs:'Voir le diagnostic et les journaux',packageOpenRecipeToBuild:'Ouvrir la recette pour construire',packageValidationStarted:'Validation lancée. Suivez l’exécution pour voir sa progression.',packagePublicationDone:'Publication réussie. Les détails du paquet se mettent à jour.'},
  de: {packageNextFailure:'Dieser Schritt ist fehlgeschlagen. Prüfen Sie Diagnose und Protokolle des Laufs vor einem neuen Versuch.',packageNextActive:'Ein Vorgang läuft. Verfolgen Sie den Lauf.',packageNextValidation:'Das Build-Artefakt kann validiert werden.',packageNextPublication:'Die Validierung war erfolgreich. Bestätigen Sie die Veröffentlichung im APT-Repository.',packageNextUnavailable:'Diese Aktion ist für den aktuellen Build-Lauf nicht verfügbar. Prüfen Sie den Lauf.',packageNextBuild:'Ein Build ist nötig. Öffnen Sie das Rezept, um es zu prüfen und den Build zu starten.',packageNextNoRecipe:'Diesem Paket ist kein Rezept zugeordnet.',packageNextCurrent:'Keine Aktion erforderlich. Sie können das Rezept oder den Build-Lauf prüfen.',packageNextRun:'Ein Build-Lauf kann geprüft werden.',packageNextRecipe:'Prüfen Sie das Rezept, um fortzufahren.',packageViewLogs:'Diagnose und Protokolle ansehen',packageOpenRecipeToBuild:'Rezept zum Bauen öffnen',packageValidationStarted:'Validierung gestartet. Verfolgen Sie den Lauf.',packagePublicationDone:'Veröffentlichung erfolgreich. Die Paketdetails werden aktualisiert.'},
  es: {packageNextFailure:'Este paso ha fallado. Revisa el diagnóstico y los registros de la ejecución antes de reintentar.',packageNextActive:'Hay trabajo en curso. Sigue la ejecución.',packageNextValidation:'El artefacto compilado está listo para validar.',packageNextPublication:'La validación se completó. Confirma la publicación en el repositorio APT.',packageNextUnavailable:'Esta acción no está disponible para la compilación actual. Revisa la ejecución.',packageNextBuild:'Se necesita una compilación. Abre la receta para revisarla e iniciar la compilación.',packageNextNoRecipe:'No hay ninguna receta vinculada a este paquete.',packageNextCurrent:'No se requiere ninguna acción. Puedes revisar la receta o la compilación.',packageNextRun:'Hay una compilación disponible para revisar.',packageNextRecipe:'Revisa la receta para continuar.',packageViewLogs:'Ver diagnóstico y registros',packageOpenRecipeToBuild:'Abrir receta para compilar',packageValidationStarted:'Validación iniciada. Sigue la ejecución para ver el progreso.',packagePublicationDone:'Publicación correcta. Los detalles del paquete se están actualizando.'},
};
const creationChrome = {
  en: {addPackage:'Add package',packageName:'Package name',createPackageHelp:'The package and its Recipe are created together. You can customize the Recipe afterward.',packageCreateAction:'Create package',packageCreating:'Creating…',packageAlreadyExists:'A package with this name already exists.'},
  fr: {addPackage:'Ajouter un paquet',packageName:'Nom du paquet',createPackageHelp:'Le paquet et sa recette sont créés ensemble. Vous pourrez ensuite personnaliser la recette.',packageCreateAction:'Créer le paquet',packageCreating:'Création…',packageAlreadyExists:'Un paquet porte déjà ce nom.'},
  de: {addPackage:'Paket hinzufügen',packageName:'Paketname',createPackageHelp:'Paket und Rezept werden zusammen erstellt. Das Rezept kann anschließend angepasst werden.',packageCreateAction:'Paket erstellen',packageCreating:'Wird erstellt…',packageAlreadyExists:'Ein Paket mit diesem Namen existiert bereits.'},
  es: {addPackage:'Añadir paquete',packageName:'Nombre del paquete',createPackageHelp:'El paquete y su receta se crean juntos. Después puedes personalizar la receta.',packageCreateAction:'Crear paquete',packageCreating:'Creando…',packageAlreadyExists:'Ya existe un paquete con este nombre.'},
};
const removalChrome = {
  en: {removePackage:'Remove package',removePackageHelp:'Remove this package from the managed catalog and APT repository.',removePublicationEffect:'Package and all of its APT publications will be removed.',keepRecipeEffect:'The Recipe will remain.',keepRunsEffect:'Historical Runs will remain.',confirmPackageRemoval:'I understand and want to remove this package.',packageRemoving:'Removing…'},
  fr: {removePackage:'Supprimer le paquet',removePackageHelp:'Supprimez ce paquet du catalogue géré et du dépôt APT.',removePublicationEffect:'Le paquet et toutes ses publications APT seront supprimés.',keepRecipeEffect:'La recette sera conservée.',keepRunsEffect:'Les exécutions historiques seront conservées.',confirmPackageRemoval:'Je comprends et souhaite supprimer ce paquet.',packageRemoving:'Suppression…'},
  de: {removePackage:'Paket entfernen',removePackageHelp:'Dieses Paket aus dem verwalteten Katalog und APT-Repository entfernen.',removePublicationEffect:'Das Paket und alle APT-Veröffentlichungen werden entfernt.',keepRecipeEffect:'Das Rezept bleibt erhalten.',keepRunsEffect:'Historische Läufe bleiben erhalten.',confirmPackageRemoval:'Ich verstehe dies und möchte das Paket entfernen.',packageRemoving:'Wird entfernt…'},
  es: {removePackage:'Eliminar paquete',removePackageHelp:'Elimina este paquete del catálogo gestionado y del repositorio APT.',removePublicationEffect:'Se eliminarán el paquete y todas sus publicaciones APT.',keepRecipeEffect:'La receta se conservará.',keepRunsEffect:'Las ejecuciones históricas se conservarán.',confirmPackageRemoval:'Lo entiendo y quiero eliminar este paquete.',packageRemoving:'Eliminando…'},
};
const updateChrome = {
  en: {overviewUpdateAction:'Build update',overviewUpdateInfo:'Start a Build with the current saved Recipe. Server automation may validate or publish the artifact afterward.',overviewUpdateUnavailable:'This update or Recipe has changed. Review the current package before starting a Build.',overviewStartBuild:'Start Build',overviewBuildQueued:'Build queued. Open the new Run to follow its progress.',packageNextUpdate:'A new version is available. Build it from the saved Recipe.'},
  fr: {overviewUpdateAction:'Construire la mise à jour',overviewUpdateInfo:'Lancez une construction avec la recette enregistrée. L’automatisation du serveur peut ensuite valider ou publier l’artéfact.',overviewUpdateUnavailable:'Cette mise à jour ou cette recette a changé. Vérifiez le paquet actuel avant de construire.',overviewStartBuild:'Lancer la construction',overviewBuildQueued:'Construction en attente. Ouvrez la nouvelle exécution pour suivre sa progression.',packageNextUpdate:'Une nouvelle version est disponible. Construisez-la avec la recette enregistrée.'},
  de: {overviewUpdateAction:'Update bauen',overviewUpdateInfo:'Build mit dem aktuell gespeicherten Rezept starten. Die Serverautomatisierung kann das Artefakt anschließend validieren oder veröffentlichen.',overviewUpdateUnavailable:'Dieses Update oder Rezept hat sich geändert. Prüfen Sie das aktuelle Paket vor dem Build.',overviewStartBuild:'Build starten',overviewBuildQueued:'Build eingereiht. Öffnen Sie den neuen Lauf, um den Fortschritt zu verfolgen.',packageNextUpdate:'Eine neue Version ist verfügbar. Bauen Sie sie mit dem gespeicherten Rezept.'},
  es: {overviewUpdateAction:'Compilar actualización',overviewUpdateInfo:'Inicia una compilación con la receta guardada. La automatización del servidor puede validar o publicar después el artefacto.',overviewUpdateUnavailable:'Esta actualización o receta ha cambiado. Revisa el paquete actual antes de compilar.',overviewStartBuild:'Iniciar compilación',overviewBuildQueued:'Compilación en cola. Abre la nueva ejecución para seguir el progreso.',packageNextUpdate:'Hay una nueva versión disponible. Compílala con la receta guardada.'},
};
const runActionChrome = {
  en: {runActionUnavailable:'This action is no longer available for this Run. Review its current status.',runBuildUnavailable:'This Run or saved Recipe has changed. Review them before starting a Build.',runBuildInfo:'Start a new Build with the current saved Recipe. This does not resume the selected Run.',runValidationStarted:'Validation started. This Run is updating.',runPublicationDone:'Publication succeeded. This Run is updating.'},
  fr: {runActionUnavailable:'Cette action n’est plus disponible pour cette exécution. Vérifiez son état actuel.',runBuildUnavailable:'Cette exécution ou la recette enregistrée a changé. Vérifiez-les avant de construire.',runBuildInfo:'Lancez une nouvelle construction avec la recette enregistrée actuelle. L’exécution sélectionnée ne reprend pas.',runValidationStarted:'Validation lancée. Cette exécution se met à jour.',runPublicationDone:'Publication réussie. Cette exécution se met à jour.'},
  de: {runActionUnavailable:'Diese Aktion ist für diesen Lauf nicht mehr verfügbar. Prüfen Sie den aktuellen Status.',runBuildUnavailable:'Dieser Lauf oder das gespeicherte Rezept hat sich geändert. Prüfen Sie beides vor dem Build.',runBuildInfo:'Einen neuen Build mit dem aktuell gespeicherten Rezept starten. Der ausgewählte Lauf wird nicht fortgesetzt.',runValidationStarted:'Validierung gestartet. Dieser Lauf wird aktualisiert.',runPublicationDone:'Veröffentlichung erfolgreich. Dieser Lauf wird aktualisiert.'},
  es: {runActionUnavailable:'Esta acción ya no está disponible para esta ejecución. Revisa su estado actual.',runBuildUnavailable:'Esta ejecución o la receta guardada ha cambiado. Revísalas antes de compilar.',runBuildInfo:'Inicia una nueva compilación con la receta guardada actual. La ejecución seleccionada no se reanuda.',runValidationStarted:'Validación iniciada. Esta ejecución se está actualizando.',runPublicationDone:'Publicación correcta. Esta ejecución se está actualizando.'},
};
const accessibilityChrome = {
  en: {navigation:'Navigation',mainNavigation:'Main navigation',expandSidebar:'Expand sidebar',collapseSidebar:'Collapse sidebar',recipeSections:'Recipe sections',runSingular:'Run'},
  fr: {navigation:'Navigation',mainNavigation:'Navigation principale',expandSidebar:'Développer la barre latérale',collapseSidebar:'Réduire la barre latérale',recipeSections:'Sections de la recette',runSingular:'Exécution'},
  de: {navigation:'Navigation',mainNavigation:'Hauptnavigation',expandSidebar:'Seitenleiste ausklappen',collapseSidebar:'Seitenleiste einklappen',recipeSections:'Rezeptabschnitte',runSingular:'Lauf'},
  es: {navigation:'Navegación',mainNavigation:'Navegación principal',expandSidebar:'Expandir la barra lateral',collapseSidebar:'Contraer la barra lateral',recipeSections:'Secciones de la receta',runSingular:'Ejecución'},
};
export function t(code, language = 'en') {return translations[language]?.[code] || extra[language]?.[code] || editorChrome[language]?.[code] || recipeJsonChrome[language]?.[code] || recipeValidationChrome[language]?.[code] || persistenceChrome[language]?.[code] || runChrome[language]?.[code] || updateChrome[language]?.[code] || runActionChrome[language]?.[code] || overviewChrome[language]?.[code] || packageChrome[language]?.[code] || creationChrome[language]?.[code] || removalChrome[language]?.[code] || accessibilityChrome[language]?.[code] || planLabels[language]?.[code] || translations.en[code] || extra.en[code] || editorChrome.en[code] || recipeJsonChrome.en[code] || recipeValidationChrome.en[code] || persistenceChrome.en[code] || runChrome.en[code] || updateChrome.en[code] || runActionChrome.en[code] || overviewChrome.en[code] || packageChrome.en[code] || creationChrome.en[code] || removalChrome.en[code] || accessibilityChrome.en[code] || code;}
export function setLocale(value) {const selected = translations[value] ? value : 'en'; locale.set(selected); localStorage.setItem(key, selected); document.documentElement.lang = selected;}
export function initLocale() {setLocale(localStorage.getItem(key));}
export function when(value, language = 'en') {if (!value) return '—'; const date = new Date(typeof value === 'number' && value < 1e12 ? value * 1000 : value); return Number.isNaN(date.valueOf()) ? String(value) : new Intl.DateTimeFormat(language, {dateStyle:'medium',timeStyle:'short'}).format(date);}
export function number(value, language = 'en') {return new Intl.NumberFormat(language).format(value || 0);}

const statusLabels = {
    en: {validation_failed:'Validation failed',publication_failed:'Publication failed',ready_to_publish:'Ready to publish',update_available:'Update available',validation_needed:'Validation needed',not_reached:'Not reached',build_failed:'Build failed',up_to_date:'Up to date',prepared:'Prepared',queued:'Queued',running:'Running',cancelled:'Cancelled',failed:'Failed',completed:'Completed',success:'Success',ok:'Available',warning:'Warning',unknown:'Unknown'},
    fr: {validation_failed:'Validation échouée',publication_failed:'Publication échouée',ready_to_publish:'Prêt à publier',update_available:'Mise à jour disponible',validation_needed:'Validation requise',not_reached:'Non atteinte',build_failed:'Construction échouée',up_to_date:'À jour',prepared:'Préparé',queued:'En attente',running:'En cours',cancelled:'Annulé',failed:'Échec',completed:'Terminé',success:'Réussi',ok:'Disponible',warning:'Avertissement',unknown:'Inconnu'},
    de: {validation_failed:'Validierung fehlgeschlagen',publication_failed:'Veröffentlichung fehlgeschlagen',ready_to_publish:'Bereit zur Veröffentlichung',update_available:'Update verfügbar',validation_needed:'Validierung nötig',not_reached:'Nicht erreicht',build_failed:'Build fehlgeschlagen',up_to_date:'Aktuell',prepared:'Vorbereitet',queued:'Eingereiht',running:'Läuft',cancelled:'Abgebrochen',failed:'Fehlgeschlagen',completed:'Abgeschlossen',success:'Erfolgreich',ok:'Verfügbar',warning:'Warnung',unknown:'Unbekannt'},
    es: {validation_failed:'Validación fallida',publication_failed:'Publicación fallida',ready_to_publish:'Listo para publicar',update_available:'Actualización disponible',validation_needed:'Validación necesaria',not_reached:'No alcanzada',build_failed:'Compilación fallida',up_to_date:'Actualizado',prepared:'Preparado',queued:'En cola',running:'En curso',cancelled:'Cancelado',failed:'Fallido',completed:'Completado',success:'Correcto',ok:'Disponible',warning:'Aviso',unknown:'Desconocido'},
  };
const lifecycleLabels = {
  en: {ready_to_validate:'Ready to validate',publication_available:'Publication available',validation_cancelled:'Validation cancelled',building:'Building',validating:'Validating',publishing:'Publishing',build_required:'Build required',recipe_missing:'Recipe missing',pending:'Pending',cancelling:'Cancelling'},
  fr: {ready_to_validate:'Prêt à valider',publication_available:'Publication disponible',validation_cancelled:'Validation annulée',building:'Construction en cours',validating:'Validation en cours',publishing:'Publication en cours',build_required:'Construction requise',recipe_missing:'Recette manquante',pending:'En attente',cancelling:'Annulation en cours'},
  de: {ready_to_validate:'Bereit zur Validierung',publication_available:'Veröffentlichung verfügbar',validation_cancelled:'Validierung abgebrochen',building:'Build läuft',validating:'Validierung läuft',publishing:'Veröffentlichung läuft',build_required:'Build erforderlich',recipe_missing:'Rezept fehlt',pending:'Ausstehend',cancelling:'Wird abgebrochen'},
  es: {ready_to_validate:'Listo para validar',publication_available:'Publicación disponible',validation_cancelled:'Validación cancelada',building:'Compilando',validating:'Validando',publishing:'Publicando',build_required:'Compilación necesaria',recipe_missing:'Falta la receta',pending:'Pendiente',cancelling:'Cancelando'},
};
export function statusLabel(value, language = 'en') {
  const translated = lifecycleLabels[language]?.[value] || statusLabels[language]?.[value] || t(value,language);
  return translated === value ? String(value || '—').replaceAll('_',' ') : translated;
}
